### ISSUE TITLE
this bug occure in last version (1.7.2)

### ISSUE THREAD

**Issue by rasoulinejad** [lingochamp/FileDownloader#1002]
java.lang.IllegalArgumentException: can't handover the message, no master to receive this message(status[3]) size[3]
	at com.liulishuo.filedownloader.FileDownloadMessenger.handoverMessage(FileDownloadMessenger.java:254)
	at com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.dispose(FileDownloadMessageStation.java:169)
	at com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.handleMessage(FileDownloadMessageStation.java:160)

![untitled](https://user-images.githubusercontent.com/21033999/38776027-a2bab728-407f-11e8-801b-fd31be29226a.png)

**Comment by rantianhua** [comment]
Please refer to #943
