### ISSUE TITLE
FileDownloadOutOfSpaceException

### ISSUE THREAD

**Issue by AhmadullahSaikat** [lingochamp/FileDownloader#1033]
com.liulishuo.filedownloader.exception.FileDownloadOutOfSpaceException: The file is too large to store, breakpoint in bytes:  0, required space in bytes: 3485930, but free space in bytes: 1305600
        at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.handlePreAllocate(DownloadLaunchRunnable.java:759)
        at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by rantianhua** [comment]
The description of the exception is clear, your storage space is not enough, so you need to remove some files you don't want to save your storage space.
