### ISSUE TITLE
Android O, startService

### ISSUE THREAD

**Issue by angcyo** [lingochamp/FileDownloader#1043]
我在Application中的onCreate回调,  init FileDownloader.

当正常启动APP时, init 正常;

但是当APP被系统释放, 保活SDK启动Application时, 就会提示:

Not allowed to start service Intent { cmp=com.hn.d.valley/com.liulishuo.filedownloader.services.FileDownloadService$SharedMainProcessService }: app is in background uid UidRecord{4d575a1 u0a154 CEM  idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1517)
	at android.app.ContextImpl.startService(ContextImpl.java:1473)
	at android.content.ContextWrapper.startService(ContextWrapper.java:644)
	at com.liulishuo.filedownloader.FileDownloadServiceSharedTransmit.bindStartByContext(FileDownloadServiceSharedTransmit.java:148)
	at com.liulishuo.filedownloader.FileDownloadServiceSharedTransmit.bindStartByContext(FileDownloadServiceSharedTransmit.java:133)
	at com.liulishuo.filedownloader.FileDownloadServiceProxy.bindStartByContext(FileDownloadServiceProxy.java:115)
	at com.liulishuo.filedownloader.FileDownloader.bindService(FileDownloader.java:495)

这个错误在Android O以上,才会出现;  

是不是可以直接try 这个错误呢?
或者可以不采用Service的方式实现么?

**Comment by angcyo** [comment]
#1017
