### ISSUE TITLE
URL not working in latest version 

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#1098]
it works fine in older version  v1.6.9 file downloader 

https://d25.ytcore.org/sse/?jobid=c9bebdc68987ab7ea78bf4a1079d035c

08-21 16:02:07.017 31219-31219/com.gagate.ggdm W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
        at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
        at com.android.okhttp.Connection.connect(Connection.java:143)
08-21 16:02:07.018 31219-31219/com.gagate.ggdm W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
        at com.liulishuo.filedownloader.connection.FileDownloadUrlConnection.execute(FileDownloadUrlConnection.java:109)
        at com.liulishuo.filedownloader.download.ConnectTask.connect(ConnectTask.java:92)
        at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.trialConnect(DownloadLaunchRunnable.java:366)
        at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:240)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by Jeffin21** [comment]
changed to http still not downloading ,

**Comment by rantianhua** [comment]
It tried and it worked , so could you please provide your log info?

**Comment by Jeffin21** [comment]
08-27 11:35:57.216 3420-3420/com.gagate.gdm W/System.err:     at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
        at com.liulishuo.filedownloader.connection.FileDownloadUrlConnection.execute(FileDownloadUrlConnection.java:107)
        at com.liulishuo.filedownloader.download.ConnectTask.connect(ConnectTask.java:100)
        at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.trialConnect(DownloadLaunchRunnable.java:365)
        at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:239)

**Comment by rantianhua** [comment]
Please provide the detail log, we cannot find clear error in this log.

**Comment by Jeffin21** [comment]
08-27 13:58:53.998 14939-14939/com.gagate.gdm W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-27 13:58:53.999 14939-14939/com.gagate.gdm W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
        at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
        at com.android.okhttp.Connection.connect(Connection.java:143)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
        at com.liulishuo.filedownloader.connection.FileDownloadUrlConnection.execute(FileDownloadUrlConnection.java:107)
        at com.liulishuo.filedownloader.download.ConnectTask.connect(ConnectTask.java:100)
        at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.trialConnect(DownloadLaunchRunnable.java:365)
        at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:239)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
    Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:324)
        at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
        at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
    	... 18 more
    Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
    	... 24 more

**Comment by rantianhua** [comment]
I am confused that SSLHandshakeException occurred if you changed to http. Can you sure you use http instead of https?
