### ISSUE TITLE
 Can't rename the  temp downloaded

### ISSUE THREAD

**Issue by lisawangli** [lingochamp/FileDownloader#1192]
java.io.IOException: Can't rename the  temp downloaded file(/storage/emulated/0/download/videonew/02、故事学英语-问姓名.mp4.temp) to the target file(/storage/emulated/0/download/videonew/02、故事学英语-问姓名.mp4)
2019-02-20 21:37:37.737 7993-7993/com.yuelt.nim.kinship W/System.err:     at com.liulishuo.filedownloader.download.DownloadStatusCallback.renameTempFile(DownloadStatusCallback.java:316)
2019-02-20 21:37:37.737 7993-7993/com.yuelt.nim.kinship W/System.err:     at com.liulishuo.filedownloader.download.DownloadStatusCallback.handleCompleted(DownloadStatusCallback.java:381)
2019-02-20 21:37:37.737 7993-7993/com.yuelt.nim.kinship W/System.err:     at com.liulishuo.filedownloader.download.DownloadStatusCallback.onCompletedDirectly(DownloadStatusCallback.java:197)
2019-02-20 21:37:37.737 7993-7993/com.yuelt.nim.kinship W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:336)
2019-02-20 21:37:37.737 7993-7993/com.yuelt.nim.kinship W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-02-20 21:37:37.738 7993-7993/com.yuelt.nim.kinship W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-02-20 21:37:37.738 7993-7993/com.yuelt.nim.kinship W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by xanahopper** [comment]
我也遇到了同样的问题

**Comment by xanahopper** [comment]
> 我也遇到了同样的问题

忘了从哪个 issue 里面看到的了，报 rename 错误是因为没有写 INTERNET 权限，加上就好了

**Comment by yangwuan55** [comment]
@xanahopper 应该不是 我也遇到同样的问题 我这边只有在小米平板4plus上会出现 其他机型都没有

**Comment by yangwuan55** [comment]
Can't rename the  temp downloaded file(/data/user/0/com.kaochong.vip/files/play_cache/NB155064356090916950492480880957/584fdd177b0027da68b167631bfbc9ae.temp) to the target file(/data/user/0/com.kaochong.vip/files/play_cache/NB155064356090916950492480880957/584fdd177b0027da68b167631bfbc9ae)

**Comment by JustDoI** [comment]
> Can't rename the temp downloaded file(/data/user/0/com.kaochong.vip/files/play_cache/NB155064356090916950492480880957/584fdd177b0027da68b167631bfbc9ae.temp) to the target file(/data/user/0/com.kaochong.vip/files/play_cache/NB155064356090916950492480880957/584fdd177b0027da68b167631bfbc9ae)

可以看看是不是文件下载失败大小为0才导致的无法rename

**Comment by yangwuan55** [comment]
> > Can't rename the temp downloaded file(/data/user/0/com.kaochong.vip/files/play_cache/NB155064356090916950492480880957/584fdd177b0027da68b167631bfbc9ae.temp) to the target file(/data/user/0/com.kaochong.vip/files/play_cache/NB155064356090916950492480880957/584fdd177b0027da68b167631bfbc9ae)
> 
> 可以看看是不是文件下载失败大小为0才导致的无法rename

是不是可以在库中做这个判断，因为这个临时文件是在下载库中创建的，报的错误也是，如果外部去判断这个临时文件的大小，以后实现变了就会出问题。

**Comment by rantianhua** [comment]
我会考虑在库内部判断下是否因为文件大小为 0 导致无法 rename 成功。

**Comment by rantianhua** [comment]
@JustDoI 我试过了，文件为 0 和 rename 不成功没有必然联系。我的测试链接：https://cdn.llscdn.com/misc/filedownloader_test-d41d8cd98f00b204e9800998ecf8427e.txt

**Comment by rantianhua** [comment]
参考 https://stackoverflow.com/questions/1325388/how-to-find-out-why-renameto-failed/1325458#1325458 ，可能有文件扫描类的进程打开了当前文件，所以导致此时 rename 失败。我检查了 FileDownloader 内部，可以确保的是，在 rename 之前已经把文件流关闭了。而且这应该是偶现的问题，大多数情况下重试下载应该 OK 的。

**Comment by alen252** [comment]
我这边Google的Android11手机必现

**Comment by jhwsx** [comment]
我这边一个车机上也遇到了，但不是必现。1.7.3版本。
