### ISSUE TITLE
 com.liulishuo.filedownloader.exception.PathConflictException

### ISSUE THREAD

**Issue by lisawangli** [lingochamp/FileDownloader#1193]
com.liulishuo.filedownloader.exception.PathConflictException: There is an another running task(2022978154) with the same downloading path(/storage/emulated/0/download/videonew/01、故事学英语-打招呼.mp4.temp), because of they are with the same target-file-path(/storage/emulated/0/download/videonew/01、故事学英语-打招呼.mp4), so if the current task is started, the path of the file is sure to be written by multiple tasks, it is wrong, then you receive this exception to avoid such conflict.
2019-02-20 21:40:20.015 7993-7993/com.yuelt.nim.kinship W/System.err:     at com.liulishuo.filedownloader.util.FileDownloadHelper.inspectAndInflowConflictPath(FileDownloadHelper.java:258)
2019-02-20 21:40:20.015 7993-7993/com.yuelt.nim.kinship W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadManager.start(FileDownloadManager.java:114)
2019-02-20 21:40:20.015 7993-7993/com.yuelt.nim.kinship W/System.err:     at com.liulishuo.filedownloader.services.FDServiceSeparateHandler.start(FDServiceSeparateHandler.java:88)
2019-02-20 21:40:20.015 7993-7993/com.yuelt.nim.kinship W/System.err:     at com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub.onTransact(IFileDownloadIPCService.java:100)
2019-02-20 21:40:20.015 7993-7993/com.yuelt.nim.kinship W/System.err:     at android.os.Binder.execTransact(Binder.java:570)

**Comment by rantianhua** [comment]
这个报错信息已经很明显了，有什么看不懂的地方吗？
