### ISSUE TITLE
 there isn't any content need to download on -171003775--1 with the content-length is 0

### ISSUE THREAD

**Issue by lisawangli** [lingochamp/FileDownloader#1194]
com.liulishuo.filedownloader.exception.FileDownloadGiveUpRetryException: there isn't any content need to download on -171003775--1 with the content-length is 0
2019-02-21 11:42:12.173 17326-17326/com.yuelt.nim.kinship W/System.err:     at com.liulishuo.filedownloader.download.FetchDataTask.run(FetchDataTask.java:91)
2019-02-21 11:42:12.173 17326-17326/com.yuelt.nim.kinship W/System.err:     at com.liulishuo.filedownloader.download.DownloadRunnable.run(DownloadRunnable.java:121)
2019-02-21 11:42:12.174 17326-17326/com.yuelt.nim.kinship W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.realDownloadWithSingleConnection(DownloadLaunchRunnable.java:609)
2019-02-21 11:42:12.174 17326-17326/com.yuelt.nim.kinship W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:295)
2019-02-21 11:42:12.174 17326-17326/com.yuelt.nim.kinship W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-02-21 11:42:12.174 17326-17326/com.yuelt.nim.kinship W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-02-21 11:42:12.174 17326-17326/com.yuelt.nim.kinship W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by rantianhua** [comment]
所以你的问题是什么呢？

**Comment by rantianhua** [comment]
信息太少了，也没有提出自己的问题，单纯从你贴的部分日志看的，是因为没有内容可以下载，如果可以的话请提供你的下载链接我这边尝试复现。
