### ISSUE TITLE
关于SSL Handshake failed导致下载失败。（三星S8没问题，小米有问题，如红米note4x android7.0）

### ISSUE THREAD

**Issue by Ezreall** [lingochamp/FileDownloader#1199]
2019-03-12 17:04:46.205 2752-2752/? W/System.err: javax.net.ssl.SSLHandshakeException: Handshake failed
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.android.okhttp.Connection.connectTls(Connection.java:235)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.android.okhttp.Connection.connectSocket(Connection.java:199)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:172)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.liulishuo.filedownloader.connection.FileDownloadUrlConnection.execute(FileDownloadUrlConnection.java:106)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.liulishuo.filedownloader.download.ConnectTask.connect(ConnectTask.java:93)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.trialConnect(DownloadLaunchRunnable.java:380)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:254)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
2019-03-12 17:04:46.205 2752-2752/? W/System.err:     at java.lang.Thread.run(Thread.java:760)

**Comment by rantianhua** [comment]
所以这个是需要查握手失败的原因，这个时候还没发生任何下载呢。
