### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=11; index=11

### ISSUE THREAD

**Issue by yueshao6800** [lingochamp/FileDownloader#1225]
线上友盟统计到的问题，目前有三个手机遇到。
java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
	at android.util.SparseArray.gc(SparseArray.java:203)
	at android.util.SparseArray.put(SparseArray.java:238)
	at com.liulishuo.filedownloader.database.b.a(NoDatabaseImpl.java:107)
	at com.liulishuo.filedownloader.database.c.a(RemitDatabase.java:137)
	at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.a(DownloadLaunchRunnable.java:680)
	at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:303)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)

看了一下NoDatabaseImpl.java的源码，感觉是SparseArray非线程安全导致的。
某一个线程在remove，另一个线程在put。
这边是否需要加锁？
final SparseArray<List<ConnectionModel>> connectionModelListMap = new SparseArray<>();

**Comment by zhpanvip** [comment]
同样的crash+1

**Comment by rantianhua** [comment]
@yueshao6800  请再提供下版本

**Comment by rantianhua** [comment]
@yueshao6800 @zhpanvip 已发布 1.7.7 snapshot 并修复该问题，请先试用 1.7.7-SNAPSHOT 版本验证一下。
