### ISSUE TITLE
Android 9 download issue after reopen application.

### ISSUE THREAD

**Issue by AhmadullahSaikat** [lingochamp/FileDownloader#1278]
When I download a file & exiting from application by back press & then reopen app & resume download again then the following issues occurred.

:filedownloader E/AndroidRuntime: FATAL EXCEPTION: FileDownloader-RemitHandoverToDB
    Process: com.tos.inapppurchase_subscription_sample:filedownloader, PID: 3855
    android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032 SQLITE_READONLY_DBMOVED[1032])
        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:946)
        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
        at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:2126)
        at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:2072)
        at com.liulishuo.filedownloader.database.SqliteDatabaseImpl.update(SqliteDatabaseImpl.java:161)
        at com.liulishuo.filedownloader.database.RemitDatabase.syncCacheToDB(RemitDatabase.java:100)
        at com.liulishuo.filedownloader.database.RemitDatabase.access$200(RemitDatabase.java:39)
        at com.liulishuo.filedownloader.database.RemitDatabase$1.handleMessage(RemitDatabase.java:76)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by rantianhua** [comment]
Please provide filedownloader version.
