### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jhwsx** [lingochamp/FileDownloader#1287]
```
java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
    at android.util.SparseArray.null gc(null)(SparseArray.java:199)
    at android.util.SparseArray.null put(null)(SparseArray.java:238)
    at com.liulishuo.filedownloader.database.NoDatabaseImpl.void insertConnectionModel(com.liulishuo.filedownloader.model.ConnectionModel)(NoDatabaseImpl.java:97)
    at com.liulishuo.filedownloader.database.RemitDatabase.void insertConnectionModel(com.liulishuo.filedownloader.model.ConnectionModel)(RemitDatabase.java:132)
    at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.void realDownloadWithMultiConnectionFromBeginning(long,int)(DownloadLaunchRunnable.java:651)
    at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.void run()(DownloadLaunchRunnable.java:303)
    at java.util.concurrent.ThreadPoolExecutor.null runWorker(null)(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.null run(null)(ThreadPoolExecutor.java:641)
    at java.lang.Thread.null run(null)(Thread.java:764)
```
```
java.lang.ArrayIndexOutOfBoundsException: src.length=23 srcPos=-19 dst.length=23 dstPos=-18 length=40
    at java.lang.System.arraycopy(System.java:629)
    at com.android.internal.util.GrowingArrayUtils.insert(GrowingArrayUtils.java:150)
    at android.util.SparseArray.put(SparseArray.java:244)
    at com.liulishuo.filedownloader.database.NoDatabaseImpl.insertConnectionModel(NoDatabaseImpl.java:97)
    at com.liulishuo.filedownloader.database.RemitDatabase.insertConnectionModel(RemitDatabase.java:132)
    at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.realDownloadWithMultiConnectionFromBeginning(DownloadLaunchRunnable.java:651)
    at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:303)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by rantianhua** [comment]
Which version?

**Comment by jhwsx** [comment]
1.7.6

**Comment by rantianhua** [comment]
I'm fixing this problem in 1.7.7.

**Comment by jhwsx** [comment]
Is 1.7.7 going to be released soon?

**Comment by rantianhua** [comment]
1.7.7 has released.

**Comment by jhwsx** [comment]
thanks.
