### ISSUE TITLE
数组越界 ： ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by linshucong** [lingochamp/FileDownloader#1303]
现象：
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=256; index=383
    at java.lang.Byte.valueOf(Byte.java:103)
    at com.liulishuo.filedownloader.DownloadTaskHunter.c(DownloadTaskHunter.java:293)
    at com.liulishuo.filedownloader.FileDownloadMessenger.h(FileDownloadMessenger.java:172)
    at com.liulishuo.filedownloader.FileDownloadMessenger.b(FileDownloadMessenger.java:276)
    at com.liulishuo.filedownloader.FileDownloadMessageStation$1.run(FileDownloadMessageStation.java:70)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:776)

版本：
'com.liulishuo.filedownloader:library:1.7.6'

影响范围：
![image](https://user-images.githubusercontent.com/19463174/69927501-28a91700-14f3-11ea-9d5c-edca73ea8426.png)

**Comment by linshucong** [comment]
1.7.8 版本什么时候出来？

**Comment by rantianhua** [comment]
确定版本没有错？在 v1.7.6 版本里，对应 stack 的代码如下：

**DownloadTaskHunter.java:293**

```
getStatus());
```
** getStatus());**  定义如下：
```
    @Override
    public byte getStatus() {
        return mStatus;
    }
```
这里没有对数组的操作。

**Comment by linshucong** [comment]
之前的是混淆的日志。这个看的比较清楚一些。

java.lang.ArrayIndexOutOfBoundsException: length=256; index=383
    at java.lang.Byte.null valueOf(null)(Byte.java:103)
    at com.liulishuo.filedownloader.DownloadTaskHunter.void onOver()(DownloadTaskHunter.java:293)
    at com.liulishuo.filedownloader.FileDownloadMessenger.void notifyError(com.liulishuo.filedownloader.message.MessageSnapshot)(FileDownloadMessenger.java:172)
    at com.liulishuo.filedownloader.FileDownloadMessenger.void handoverMessage()(FileDownloadMessenger.java:276)
    at com.liulishuo.filedownloader.FileDownloadMessageStation$1.void run()(FileDownloadMessageStation.java:70)
    at java.util.concurrent.ThreadPoolExecutor.null runWorker(null)(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.null run(null)(ThreadPoolExecutor.java:607)
    at java.lang.Thread.null run(null)(Thread.java:761)

**Comment by rantianhua** [comment]
其实前面的也看的很清楚，因为有类名称和行号。所以确认一下你们使用的版本是否是自己改过的？

**Comment by linshucong** [comment]
![image](https://user-images.githubusercontent.com/19463174/70061318-09a7a380-161f-11ea-878d-dc68f2484d47.png)
banb版本号是确认没错的。
代码没有自己改过。

**Comment by rantianhua** [comment]
那真的很奇怪，对应的代码我上面贴过了。内部并没有调用 Byte.valueOf(Byte) 这个方法。而且内部表示 status 的变量始终都是 byte 对象。
