### ISSUE TITLE
在初始化时出现错误

### ISSUE THREAD

**Issue by itsmallsun** [lingochamp/FileDownloader#131]
java.lang.ExceptionInInitializerError
at com.liulishuo.filedownloader.util.FileDownloadProperties.getImpl(FileDownloadProperties.java:109)
                                                                                      at com.liulishuo.filedownloader.services.FileDownloadService.onCreate(FileDownloadService.java:43)
                                                                                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2731)
                                                                                      at android.app.ActivityThread.access$1800(ActivityThread.java:144)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1361)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5221)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
                                                                                   Caused by: java.lang.IllegalStateException: Please invoke the FileDownloader#init in Application#onCreate first.
                                                                                      at com.liulishuo.filedownloader.util.FileDownloadProperties.<init>(FileDownloadProperties.java:117)
                                                                                      at com.liulishuo.filedownloader.util.FileDownloadProperties$HolderClass.<clinit>(FileDownloadProperties.java:105)
                                                                                      at com.liulishuo.filedownloader.util.FileDownloadProperties.getImpl(FileDownloadProperties.java:109) 
                                                                                      at com.liulishuo.filedownloader.services.FileDownloadService.onCreate(FileDownloadService.java:43) 
                                                                                      at android.app.ActivityThread.handleCreateService(ActivityThread.java:2731) 

这是在初始化的时候报的错误:应该是有propreties引起的，弄了半天还是出现这个问题，希望您可以您可以帮我解惑

**Comment by Jacksgong** [comment]
找到原因了吗？

**Comment by Trinkes** [comment]
I'm implementing a service to use this downloader lib, but when my app is killed and the service is restarted, the fileDownloader lib is giving me this error, is there a way to use your lib without having to call the init method on application's onCreate?

thanks

**Comment by itsmallsun** [comment]
yes

**Comment by Trinkes** [comment]
how?
