### ISSUE TITLE
FileDownloadProperties

### ISSUE THREAD

**Issue by SourceAdFlt** [lingochamp/FileDownloader#1326]
#### Before Issue

1. Please search on the [Issues](https://github.com/lingochamp/FileDownloader/issues)
2. Please search on the [wiki](https://github.com/lingochamp/FileDownloader/wiki)
3. Please set `FileDownloadLog.NEED_LOG=true` and review the Logcat output from main process and `:filedownloader` process ( pay attention to Warn and Error level logcat)

#### Issue

1. What problem do you get?
2. Which version of FileDownloader are you using when you produce such problem?
3. How to reproduce such problem?
4. Do you set `FileDownloadLog.NEED_LOG=true`?
5. Could you please reproduce this problem and provide all main process and `:filedownloader` process logcat 
6. Can you fix it by yourself and request PR, if not, what's problem do you get when you try to fix it

>P.S. If you don't know how to get `:filedownloader` process, it's recommended to using `pidcat` to just filter all your application logcat, or define `process.non-separate=true` on [filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)

---

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

**Comment by SourceAdFlt** [comment]
02-22 19:00:34.737 26466 26584 W System.err: java.lang.ExceptionInInitializerError

02-22 19:00:34.737 26466 26584 W System.err: 	at com.liulishuo.filedownloader.util.FileDownloadProperties.getImpl(FileDownloadProperties.java:153)

02-22 19:00:34.737 26466 26584 W System.err: 	at com.liulishuo.filedownloader.FileDownloadServiceProxy.<init>(FileDownloadServiceProxy.java:57)

02-22 19:00:34.737 26466 26584 W System.err: 	at com.liulishuo.filedownloader.FileDownloadServiceProxy.<init>(FileDownloadServiceProxy.java:36)

02-22 19:00:34.737 26466 26584 W System.err: 	at com.liulishuo.filedownloader.FileDownloadServiceProxy$HolderClass.<clinit>(FileDownloadServiceProxy.java:39)

02-22 19:00:34.737 26466 26584 W System.err: 	at com.liulishuo.filedownloader.FileDownloadServiceProxy.getImpl(FileDownloadServiceProxy.java:43)

02-22 19:00:34.737 26466 26584 W System.err: 	at com.liulishuo.filedownloader.FileDownloader.isServiceConnected(FileDownloader.java:555)

02-22 19:00:34.737 26466 26584 W System.err: 	at com.liulishuo.filedownloader.LostServiceConnectedHandler.dispatchTaskStart(LostServiceConnectedHandler.java:122)

02-22 19:00:34.737 26466 26584 W System.err: 	at com.liulishuo.filedownloader.DownloadTaskHunter.start(DownloadTaskHunter.java:582)

02-22 19:00:34.737 26466 26584 W System.err: 	at com.liulishuo.filedownloader.FileDownloadTaskLauncher$LaunchTaskRunnable.run(FileDownloadTaskLauncher.java:155)

02-22 19:00:34.737 26466 26584 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)

02-22 19:00:34.737 26466 26584 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)

02-22 19:00:34.737 26466 26584 W System.err: 	at java.lang.Thread.run(Thread.java:818)

02-22 19:00:34.737 26466 26584 W System.err: Caused by: java.lang.IllegalStateException: Please invoke the 'FileDownloader#setup' before using FileDownloader. If you want to register some components on FileDownloader please invoke the 'FileDownloader#setupOnApplicationOnCreate' on the 'Application#onCreate' first.

02-22 19:00:34.737 26466 26584 W System.err: 	at com.liulishuo.filedownloader.util.FileDownloadProperties.<init>(FileDownloadProperties.java:162)

02-22 19:00:34.737 26466 26584 W System.err: 	at com.liulishuo.filedownloader.util.FileDownloadProperties.<init>(FileDownloadProperties.java:126)

02-22 19:00:34.737 26466 26584 W System.err: 	at com.liulishuo.filedownloader.util.FileDownloadProperties$HolderClass.<clinit>(FileDownloadProperties.java:149)

02-22 19:00:34.737 26466 26584 W System.err: 	... 12 more

02-22 19:00:34.738  2772  3034 D PhoneApp: getPreferSlotIdForRafSupported: preferslotId =0, slotId =0, maxRafSupportedPhoneId = 0
