### ISSUE TITLE
Foreground service types are required on `targetSdk` 34

### ISSUE THREAD

**Issue by Goooler** [lingochamp/FileDownloader#1421]
Invoke `Service.startForeground` on targetSdk 34 platforms, need to declared the service type, see https://developer.android.com/about/versions/14/changes/fgs-types-required

**Comment by hannanshahidfunsoltech** [comment]
same issue

**Comment by Goooler** [comment]
We might migrate to WorkManager.

**Comment by TonyAnine** [comment]
same issue

**Comment by Goooler** [comment]
<strike>
Workaround: replace the [services declaring](https://github.com/lingochamp/FileDownloader/blob/6237a8cac174bcc916e4342b14ab1ab72a5768d4/library/src/main/AndroidManifest.xml#L7-L12) in your manifest like:

```xml
    <application>
        <service android:name="com.liulishuo.filedownloader.services.FileDownloadService$SharedMainProcessService"
            android:foregroundServiceType="shortService"
            tools:node="replace"/>
        <service
            android:name="com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService"
            android:process=":filedownloader"
            android:foregroundServiceType="shortService"
            tools:node="replace"/>
    </application>
```
</strike>

or you can try out my fork, see:

- https://github.com/Goooler/FileDownloader
- https://central.sonatype.com/artifact/io.github.goooler.android/filedownloader-fork

**Comment by hannanshahidfunsoltech** [comment]
same error check with both library change and manifest deceleration @Goooler   

` android.app.InvalidForegroundServiceTypeException: Starting FGS with type none callerApp=ProcessRecord{a82e4e6 23516:com.diwn/u0a452} targetSDK=34 has been prohibited
                                                                                                    	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:53)
                                                                                                    	at android.app.InvalidForegroundServiceTypeException$1.createFromParcel(InvalidForegroundServiceTypeException.java:49)
                                                                                                    	at android.os.Parcel.readParcelableInternal(Parcel.java:4900)
                                                                                                    	at android.os.Parcel.readParcelable(Parcel.java:4882)
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3082)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3071)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3054)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2996)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
                                                                                                    	at android.app.Service.startForeground(Service.java:862)
                                                                                                    	at androidx.work.impl.foreground.SystemForegroundService$Api31Impl.startForeground(SystemForegroundService.java:194)
                                                                                                    	at androidx.work.impl.foreground.SystemForegroundService$1.run(SystemForegroundService.java:130)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:257)
                                                                                                    	at android.os.Looper.loop(Looper.java:368)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)`

**Comment by Goooler** [comment]
Try 1.7.9

**Comment by 121104115wyb** [comment]
请看这个 https://issuetracker.google.com/issues/307329994?pli=1
加个校验在sdk 34 时替换掉 START_STICKY
