### ISSUE TITLE
红米的android 13部分手机会出现SecurityException

### ISSUE THREAD

**Issue by haoYeaph** [lingochamp/FileDownloader#1430]
java.lang.SecurityException: Unable to start service Intent { cmp=com.ld.phonestore/com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService (has extras) }: Unable to launch app com.ld.phonestore/10239 for service Intent { cmp=com.ld.phonestore/com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService }: process is bad
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1916)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1880)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:832)

**Comment by alen252** [comment]
遇到同样的问题

**Comment by 1345241828** [comment]
你好，请问解决了吗
