### ISSUE TITLE
运行中发现一个String format的异常

### ISSUE THREAD

**Issue by pzhangleo** [lingochamp/FileDownloader#175]
看代码应该是%d对应的字段缺失了，版本是0.3.1
异常信息如下：
java.util.MissingFormatArgumentException: Format specifier: d
	at java.util.Formatter.getArgument(Formatter.java:1111)
	at java.util.Formatter.doFormat(Formatter.java:1076)
	at java.util.Formatter.format(Formatter.java:1042)
	at java.util.Formatter.format(Formatter.java:1011)
	at java.lang.String.format(String.java:1999)
	at com.liulishuo.filedownloader.util.FileDownloadUtils.formatString(FileDownloadUtils.java:267)
	at com.liulishuo.filedownloader.services.FileDownloadRunnable.run(FileDownloadRunnable.java:174)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

**Comment by Jacksgong** [comment]
这个问题在 0.3.2 [已经修复了](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG-ZH.md#修复)。
