### ISSUE TITLE
SQLite error when trying to run download task from another activity. 

### ISSUE THREAD

**Issue by supunsithmal** [lingochamp/FileDownloader#183]
In my application, After app open download task run successfully. When i add another download task after moving to another activity,  download finished successfully but logcat showing following error log.

```
06-16 15:52:18.107 22811-23332/com.axis.drawingdesk.v3:filedownloader E/SQLiteLog: (1032) statement aborts at 18: [INSERT INTO filedownloader(etag,errMsg,status,total,sofar,path,url,_id) VALUES (?,?,?,?,?,?,?,?)] 
06-16 15:52:18.110 22811-23332/com.axis.drawingdesk.v3:filedownloader E/SQLiteDatabase: Error inserting etag=null errMsg=null status=1 total=0 sofar=0 path={path} url={url}  _id=-1950335409
                                                                                        android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
                                                                                            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                                            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:780)
                                                                                            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                                            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                                            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
                                                                                            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1341)
                                                                                            at com.liulishuo.filedownloader.services.FileDownloadDBHelper.insert(FileDownloadDBHelper.java:143)
                                                                                            at com.liulishuo.filedownloader.services.FileDownloadDBHelper.update(FileDownloadDBHelper.java:162)
                                                                                            at com.liulishuo.filedownloader.services.FileDownloadMgr.start(FileDownloadMgr.java:116)
                                                                                            at com.liulishuo.filedownloader.services.FDServiceSeparateHandler.start(FDServiceSeparateHandler.java:102)
                                                                                            at com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub.onTransact(IFileDownloadIPCService.java:125)
                                                                                            at android.os.Binder.execTransact(Binder.java:453)
```

app is not crashing or anything and downloads are successful. but above error appear in logcat with every link download. Did i miss something? The code is same as [https://github.com/lingochamp/FileDownloader/wiki/Start-downloading#start-downloading-task-queue](url)  and i use 1st method.

**Comment by Jacksgong** [comment]
Sorry, I missed this Issus before.

---

It is so oddball, The filedownloader database stores in your application internal data folder, normally your application has read、write、execute permission absolutely.

**Comment by Jacksgong** [comment]
This would be the small probability case is occurred on SQLite when there are issues on devices or filesystem, so you can customize your own database to handle such issues , ref [here](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component).
