### ISSUE TITLE
下载过程中关掉网络 报错 log如下

### ISSUE THREAD

**Issue by yubang322311** [lingochamp/FileDownloader#195]
```
E/SignOutReceiver( 6565): NETWORK_STATE_CHANGED_ACTION
E/MyCrashHandler( 8907): uncaughtExceptionjava.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = java.net.SocketException)
E/MyCrashHandler( 8907): 	at android.os.Parcel.writeSerializable(Parcel.java:1388)
E/MyCrashHandler( 8907): 	at com.liulishuo.filedownloader.message.SmallMessageSnapshot$ErrorMessageSnapshot.writeToParcel(SmallMessageSnapshot.java:245)
E/MyCrashHandler( 8907): 	at com.liulishuo.filedownloader.i.IFileDownloadIPCCallback$Stub$Proxy.callback(IFileDownloadIPCCallback.java:83)
E/MyCrashHandler( 8907): 	at com.liulishuo.filedownloader.services.FDServiceSeparateHandler.callback(FDServiceSeparateHandler.java:53)
E/MyCrashHandler( 8907): 	at com.liulishuo.filedownloader.services.FDServiceSeparateHandler.receive(FDServiceSeparateHandler.java:179)
E/MyCrashHandler( 8907): 	at com.liulishuo.filedownloader.message.MessageSnapshotThreadPool$FlowSingleExecutor$1.run(MessageSnapshotThreadPool.java:102)
E/MyCrashHandler( 8907): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/MyCrashHandler( 8907): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/MyCrashHandler( 8907): 	at java.lang.Thread.run(Thread.java:818)
E/MyCrashHandler( 8907): Caused by: java.io.InvalidClassException: android.system.ErrnoException doesn't have a serializable field interfaces of type int
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:933)
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
E/MyCrashHandler( 8907): 	at java.lang.Throwable.writeObject(Throwable.java:436)
E/MyCrashHandler( 8907): 	at java.lang.reflect.Method.invoke(Native Method)
E/MyCrashHandler( 8907): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1033)
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
E/MyCrashHandler( 8907): 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
E/MyCrashHandler( 8907): 	at android.os.Parcel.writeSerializable(Parcel.java:1383)
```

**Comment by Jacksgong** [comment]
我在demo中，尝试了下载过程中，关闭网络，没有出现类似异常。

根据你的错误信息，我查看了官方文档: [InvalidClassException and serialVersionUID in Java](http://geekexplains.blogspot.com/2008/05/invalidclassexception-and.html)

这边的错误是在parcel SocketException 的时候出现的错误，具体的错误信息是:

```
java.io.InvalidClassException: android.system.ErrnoException doesn't have a serializable field interfaces of type int
```

根据官方的描述，这里应该不是FileDownloader的问题，应该是系统/编译器的错误导致`android.system.ErrnoException`在运行时找不到对应的`serialVersionUID`(原本如果没有定义，编译器应该会为实现了`Serializable`的类创建一个的)。
