### ISSUE TITLE
AndroidRuntime exception

### ISSUE THREAD

**Issue by e4basil** [lingochamp/FileDownloader#213]
`
*****.****.*** :filedownloader E/AndroidRuntime: FATAL EXCEPTION: pool-10-thread-1
                                                                                   java.lang.NullPointerException
                                                                                       at com.liulishuo.filedownloader.message.MessageSnapshotThreadPool$FlowSingleExecutor$1.run(MessageSnapshotThreadPool.java:102)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                                       at java.lang.Thread.run(Thread.java:856)
`

**Comment by Jacksgong** [comment]
What version you are using?

**Comment by e4basil** [comment]
latest (0.3.3)

**Comment by Jacksgong** [comment]
OK, Could you please describe what scenario?

**Comment by Jacksgong** [comment]
Fixed since [0.3.4](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.4).
