### ISSUE TITLE
AssertionFailedError这个异常必须抛出来么？

### ISSUE THREAD

**Issue by pzhangleo** [lingochamp/FileDownloader#215]
串行执行任务时发生的异常
junit.framework.AssertionFailedError: create serial handler list must not empty
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.liulishuo.filedownloader.FileDownloader.createSerialHandler(FileDownloader.java:571)
	at com.liulishuo.filedownloader.FileDownloader.start(FileDownloader.java:247)
	at com.liulishuo.filedownloader.FileDownloadQueueSet.start(FileDownloadQueueSet.java:146)
	at com.being.fame.service.SchedulerJobService$1.run(SchedulerJobService.java:216)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at com.being.fame.thread.WorkerHandlerThread.run(WorkerHandlerThread.java:47)

**Comment by Jacksgong** [comment]
这个异常是FileDownloader主动抛出的，是为了告知，在启动串行任务之前没有任何相同Listener的任务被`ready`

**Comment by Jacksgong** [comment]
我优化下这里，在start返回成功或失败，而不抛出来吧。

**Comment by Jacksgong** [comment]
Enhanced since [0.3.4](https://github.com/lingochamp/FileDownloader/releases/tag/v0.3.4).

**Comment by pzhangleo** [comment]
赞一个
