### ISSUE TITLE
Concurrent Modification Exception

### ISSUE THREAD

**Issue by farbod-s** [lingochamp/FileDownloader#23]
Logcat output:
`FATAL EXCEPTION: pool-2-thread-1
Process: ir.sobhe.menbar, PID: 6187
java.util.ConcurrentModificationException
at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
at com.liulishuo.filedownloader.FileDownloadTask$FileDownloadInternalLis.callback(FileDownloadTask.java:213)
at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:192)
at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.publish(DownloadEventPoolImpl.java:128)
at com.liulishuo.filedownloader.FileDownloadEventPool.publish(FileDownloadEventPool.java:111)
at com.liulishuo.filedownloader.event.DownloadEventPoolImpl$2.run(DownloadEventPoolImpl.java:159)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)`

**Comment by Jacksgong** [comment]
Thank you for your feedback, let me check.

**Comment by Jacksgong** [comment]
Sorry, Could you tell me which version of Filedownloader you are using?

**Comment by Jacksgong** [comment]
I find it, I will fix it in the next version. Thank you so much.

**Comment by farbod-s** [comment]
@Jacksgong Thanks for your quick response.
