### ISSUE TITLE
NullPointerException in init method

### ISSUE THREAD

**Issue by vicpinm** [lingochamp/FileDownloader#250]
I get this exception with some users of my app, when I call init():

Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.liulishuo.filedownloader.util.FileDownloadUtils.isDownloaderProcess(FileDownloadUtils.java:226)
       at com.liulishuo.filedownloader.FileDownloader.init(FileDownloader.java:83)
       at com.liulishuo.filedownloader.FileDownloader.init(FileDownloader.java:59)
       at com.ivoox.app.IvooxApplication.onCreate(IvooxApplication.java:75)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4638)
       at android.app.ActivityThread.access$1500(ActivityThread.java:155)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5343)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

**Comment by Jacksgong** [comment]
This Already fixed since [0.3.4](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG.md#version-034)
