### ISSUE TITLE
java.lang.Throwable report

### ISSUE THREAD

**Issue by pop1030123** [lingochamp/FileDownloader#258]
```
08-10 17:08:07.020 I/System.out(24661): Group name=java.lang.ThreadGroup[name=main,maxPriority=10], Thread Total count=121, This thread name=pool-84-thread-3
08-10 17:08:07.020 W/System.err(24661): java.lang.Throwable: stack dump
08-10 17:08:07.020 W/System.err(24661): 	at java.lang.Thread.dumpStack(Thread.java:503)
08-10 17:08:07.020 W/System.err(24661): 	at java.lang.Thread.create(Thread.java:433)
08-10 17:08:07.020 W/System.err(24661): 	at java.lang.Thread.<init>(Thread.java:355)
08-10 17:08:07.020 W/System.err(24661): 	at java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:525)
08-10 17:08:07.020 W/System.err(24661): 	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:582)
08-10 17:08:07.020 W/System.err(24661): 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:895)
08-10 17:08:07.020 W/System.err(24661): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1327)
08-10 17:08:07.020 W/System.err(24661): 	at com.liulishuo.filedownloader.services.FileDownloadThreadPool.execute(FileDownloadThreadPool.java:82)
08-10 17:08:07.020 W/System.err(24661): 	at com.liulishuo.filedownloader.services.FileDownloadMgr.start(FileDownloadMgr.java:158)
08-10 17:08:07.020 W/System.err(24661): 	at com.liulishuo.filedownloader.services.FDServiceSharedHandler.start(FDServiceSharedHandler.java:61)
08-10 17:08:07.020 W/System.err(24661): 	at com.liulishuo.filedownloader.FileDownloadServiceSharedTransmit.start(FileDownloadServiceSharedTransmit.java:55)
08-10 17:08:07.020 W/System.err(24661): 	at com.liulishuo.filedownloader.FileDownloadServiceProxy.start(FileDownloadServiceProxy.java:65)
08-10 17:08:07.020 W/System.err(24661): 	at com.liulishuo.filedownloader.FileDownloadTask._startExecute(FileDownloadTask.java:83)
08-10 17:08:07.020 W/System.err(24661): 	at com.liulishuo.filedownloader.BaseDownloadTask._start(BaseDownloadTask.java:859)
08-10 17:08:07.020 W/System.err(24661): 	at com.liulishuo.filedownloader.FileDownloadTaskLauncher$LaunchTaskRunnable.run(FileDownloadTaskLauncher.java:138)
08-10 17:08:07.020 W/System.err(24661): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-10 17:08:07.020 W/System.err(24661): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-10 17:08:07.020 W/System.err(24661): 	at java.lang.Thread.run(Thread.java:831)
```

**Comment by Jacksgong** [comment]
谢谢。我跟下源码看看。

**Comment by Jacksgong** [comment]
@pop1030123 可否给下报这个crash的系统版本。以及手机型号。

**Comment by pop1030123** [comment]
手机型号：HUAWEI P7-L07
系统版本：Android5.1.1
华为系统：EMUI系统3.1

**Comment by Jacksgong** [comment]
@pop1030123 谢谢。这个会引起CRASH吗，因为我看这个是 Warn级别的日志。

FileDownloadThreadPool中的线程池是正常的创建一个线程的时候一直走到Thread构造函数，然后走到Thread#create（行数对应方法名），然后就有调用dumpStack，然后就挂了。看源码没有看出原因。

**Comment by Jacksgong** [comment]
大概可以描述下在什么场景下遇到吗，我参考下，看看有什么线索。
