### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by e4basil** [lingochamp/FileDownloader#259]
`Fatal Exception: java.lang.NullPointerException
       at com.liulishuo.filedownloader.message.MessageSnapshotThreadPool$FlowSingleExecutor$1.run(MessageSnapshotThreadPool.java:102)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)`

**Comment by Jacksgong** [comment]
Already fixed since [v0.3.4](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG.md#version-034).

**Comment by Jacksgong** [comment]
Ref: #213

**Comment by e4basil** [comment]
thanks
