### ISSUE TITLE
请问一下,blockComplete回调不会抛到主线程吗?

### ISSUE THREAD

**Issue by Ernest-su** [lingochamp/FileDownloader#274]
`BaseDownloadTask#setSyncCallback`我没有设置,使用的是默认值`false`.
我在运行的时候遇到如下的错误:
```
E/AndroidRuntime: FATAL EXCEPTION: pool-9-thread-2
	  Process: com.konka.downloadcenter, PID: 16715
	  android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
		  at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6099)
		  at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:824)
		  at android.view.View.requestLayout(View.java:16431)
		  at android.view.View.requestLayout(View.java:16431)
		  at android.view.View.requestLayout(View.java:16431)
		  at android.view.View.requestLayout(View.java:16431)
		  at android.view.View.requestLayout(View.java:16431)
		  at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:352)
		  at android.view.View.requestLayout(View.java:16431)
		  at android.support.v7.widget.RecyclerView.requestLayout(RecyclerView.java:3291)
		  at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.triggerUpdateProcessor(RecyclerView.java:4308)
		  at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeChanged(RecyclerView.java:4275)
		  at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyItemRangeChanged(RecyclerView.java:9959)
		  at android.support.v7.widget.RecyclerView$Adapter.notifyItemChanged(RecyclerView.java:5791)
		  at com.konka.downloadcenter.manager.DownloadListUpdater.update(DownloadListUpdater.java:148)
		  at com.konka.downloadcenter.manager.DownloadManager.callGlobalUpdater(DownloadManager.java:206)
		  at com.konka.downloadcenter.manager.DownloadManager.access$000(DownloadManager.java:30)
		  at com.konka.downloadcenter.manager.DownloadManager$1.blockComplete(DownloadManager.java:102)
		  at com.liulishuo.filedownloader.FileDownloadListener.callback(FileDownloadListener.java:86)
		  at com.liulishuo.filedownloader.FileDownloadMessenger.handoverMessage(FileDownloadMessenger.java:255)
		  at com.liulishuo.filedownloader.FileDownloadMessageStation$1.run(FileDownloadMessageStation.java:80)
		  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
		  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
		  at java.lang.Thread.run(Thread.java:841)
```
在`FileDownloadMessageStation`中,我看到有这样的一段代码(76~84行)
```
        if (messenger.isBlockingCompleted()) {
            blockCompletedPool.execute(new Runnable() {
                @Override
                public void run() {
                    messenger.handoverMessage();
                }
            });
            return;
        }
```

**Comment by Jacksgong** [comment]
是的，默认情况下所有回调只有 `blockComplete` 不会抛回主线程。

首先这个回调的作用是，到`blockComplete`的时候其实已经下载完成了。此时可以在这里做一些解压缩或者编解码相关的操作。`blockComplete` 回调结束后，会立马抛`completed`回调到主线程。

**Comment by Jacksgong** [comment]
如果你没有相关需求，可以直接忽略 `blockComplete`回调，直接到 `completed`中做下载结束后的UI更新。

**Comment by Ernest-su** [comment]
好的.明白了.

**Comment by viphsx123** [comment]
但是completed不会回调到主线程吧，不仅仅是blockComplete

**Comment by Jacksgong** [comment]
@viphsx123 只有 `blockComplete`会在非主线程，其他的方法默认都是在 主线程回调，包括`completed` 。
