### ISSUE TITLE
Why I can't start FileDownloader in Activity with FileDownloader.init(getApplication());

### ISSUE THREAD

**Issue by olchtar** [lingochamp/FileDownloader#28]
I'm developing a library that use FileDownloader as Download Engine. But I don't want to suppress creation of Application class. Because of that I prefer use Activities only. When I start FileDownloader with FileDownloader.init(getApplication()) in Activity then start a DownloadTask FileDownloader Service throw this error:
```

02-07 11:22:36.370 32492-32492/com.***.library:filedownloader E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.***.library:filedownloader, PID: 32492
java.lang.RuntimeException: Unable to create service com.liulishuo.filedownloader.services.FileDownloadService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.sqlite.SQLiteDatabase android.content.Context.openOrCreateDatabase(java.lang.String, int, android.database.sqlite.SQLiteDatabase$CursorFactory, android.database.DatabaseErrorHandler)' on a null object reference
    at android.app.ActivityThread.handleCreateService(ActivityThread.java:3684)
    at android.app.ActivityThread.access$2000(ActivityThread.java:218)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6914)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.sqlite.SQLiteDatabase android.content.Context.openOrCreateDatabase(java.lang.String, int, android.database.sqlite.SQLiteDatabase$CursorFactory, android.database.DatabaseErrorHandler)' on a null object reference
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
    at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
    at com.liulishuo.filedownloader.services.FileDownloadDBHelper.<init>(FileDownloadDBHelper.java:49)
    at com.liulishuo.filedownloader.services.FileDownloadMgr.<init>(FileDownloadMgr.java:47)
    at com.liulishuo.filedownloader.services.FileDownloadService$FileDownloadServiceBinder.<init>(FileDownloadService.java:78)
    at com.liulishuo.filedownloader.services.FileDownloadService$FileDownloadServiceBinder.<init>(FileDownloadService.java:72)
    at com.liulishuo.filedownloader.services.FileDownloadService.createBinder(FileDownloadService.java:54)
    at com.liulishuo.filedownloader.services.FileDownloadService.createBinder(FileDownloadService.java:33)
    at com.liulishuo.filedownloader.services.BaseFileService.onCreate(BaseFileService.java:66)
    at com.liulishuo.filedownloader.services.FileDownloadService.onCreate(FileDownloadService.java:39)
    at android.app.ActivityThread.handleCreateService(ActivityThread.java:3674)
    at android.app.ActivityThread.access$2000(ActivityThread.java:218) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1801) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:145) 
    at android.app.ActivityThread.main(ActivityThread.java:6914) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:372) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
```
What should I do? What is the difference between FileDownloader.init(this) in Application and FileDownloader.init(getApplication()) in Activity?

**Comment by Jacksgong** [comment]
When the progress `:filedownloader` is launching, The progress `:filedownloader` will invoke `Application#onCreate` to init progress.


---

And with the `FileDownloader#init(Application)` just cache the `ApplicationContext`, I can't understand What are you worried about?

**Comment by olchtar** [comment]
I got it. Thanks for this library and fast answer :+1:

**Comment by Jacksgong** [comment]
:)

**Comment by deepinder10** [comment]
I am facing the same error as shown above. Can you help?

**Comment by rharesh90** [comment]
Hello 
I have implement FileDownloader Library. and it's working fine . but when download file at that time  if network is switch or disconnected. than after getting network i download is not restart automatically .  so Please help me

**Comment by Jacksgong** [comment]
@rharesh90 Sorry FileDownloader is a pure downloader engine, If you have such feature, you can handle it by your upper layer:

1. You can have you own [DownloadManager](https://github.com/lingochamp/FileDownloader/issues/103#issuecomment-209173124).
2. If occur `error` callback with the network is disconnected, you `reuse` and store those tasks.
3. When you receive the network changed broadcast with network is reconnected, just start all tasks you stored.
