### ISSUE TITLE
Fatal Exception: java.util.IllegalFormatConversionException

### ISSUE THREAD

**Issue by rajnishmishra20** [lingochamp/FileDownloader#30]
Fatal Exception: java.util.IllegalFormatConversionException: %d can't format java.lang.String arguments
       at java.util.Formatter.badArgumentType(Formatter.java:1489)
       at java.util.Formatter.transformFromInteger(Formatter.java:1689)
       at java.util.Formatter.transform(Formatter.java:1461)
       at java.util.Formatter.doFormat(Formatter.java:1081)
       at java.util.Formatter.format(Formatter.java:1042)
       at java.util.Formatter.format(Formatter.java:1011)
       at java.lang.String.format(String.java:1803)
       at java.lang.String.format(String.java:1777)
       at com.liulishuo.filedownloader.util.FileDownloadLog.log(FileDownloadLog.java:64)
       at com.liulishuo.filedownloader.util.FileDownloadLog.log(FileDownloadLog.java:55)
       at com.liulishuo.filedownloader.util.FileDownloadLog.d(FileDownloadLog.java:43)
       at com.liulishuo.filedownloader.FileDownloadEventPool.publish(FileDownloadEventPool.java:100)
       at com.liulishuo.filedownloader.FileDownloadEventPool$WaitingRunnable.loopMessage(FileDownloadEventPool.java:372)
       at com.liulishuo.filedownloader.FileDownloadEventPool$WaitingRunnable.access$400(FileDownloadEventPool.java:197)
       at com.liulishuo.filedownloader.FileDownloadEventPool$WaitingRunnable$1.run(FileDownloadEventPool.java:313)
       at android.os.Handler.handleCallback(Handler.java:810)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:189)
       at android.app.ActivityThread.main(ActivityThread.java:5532)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)

**Comment by Jacksgong** [comment]
Thank you very much for your feedback. I will fix it immediately.

---

ps: You can set `FileDownloadLog.NEED_LOG = false`(default) to avoid such exception.

**Comment by rajnishmishra20** [comment]
Thanks for the quick response.

**Comment by Jacksgong** [comment]
:)

**Comment by Jacksgong** [comment]
Fixed in [v0.2.1](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.1).
