### ISSUE TITLE
cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:118)

### ISSUE THREAD

**Issue by JChord** [lingochamp/FileDownloader#333]
1.1.0的线程池很容易出现这个错误
```
java.lang.StackOverflowError
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:177)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:256)
	at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:386)
	at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:118)
	at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
	at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
```

**Comment by Jacksgong** [comment]
今天的1.1.5会带上。已经修复了。Ref #321
