### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by e4basil** [lingochamp/FileDownloader#344]
Fatal Exception: java.lang.RuntimeException: mStatus undefined, -2
       at com.liulishuo.filedownloader.DownloadTaskHunter.setStatus(DownloadTaskHunter.java:533)
       at com.liulishuo.filedownloader.DownloadTaskHunter.pause(DownloadTaskHunter.java:391)
       at com.liulishuo.filedownloader.DownloadTask.pause(DownloadTask.java:338)
       at com.liulishuo.filedownloader.FileDownloader.pauseAll(FileDownloader.java:283)
       at com.adkaar.adkaarapp.ui.MainActivity.pause(MainActivity.java:872)
       at com.adkaar.adkaarapp.ui.MainActivity.access$300(MainActivity.java:90)
       at com.adkaar.adkaarapp.ui.MainActivity$6.onClick(MainActivity.java:588)
       at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5341)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Jacksgong** [comment]
I saw the code, this seems to be impossible. What the FileDownloader version are you using?

**Comment by e4basil** [comment]
1.1.0

**Comment by Jacksgong** [comment]
Okey, That's confuse... I have no idea with it. In the [source code](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/DownloadTaskHunter.java#L531), we throw this exception only if `mStatus` is greater than `6`(`FileDownloadStatus.MAX_INT`) or less than `-4`(`FileDownloadStatus.MIN_INT`)...

How often did you occur such problem, Is it possible the problem in the custom JVM ?

**Comment by e4basil** [comment]
it occurs just one time in my friend's Lenovo P70-A(android 4.4.4)

**Comment by Jacksgong** [comment]
Thanks, If you occur this problem once again, I will reopen this issue.
