### ISSUE TITLE
偶尔出现异常java.util.MissingFormatArgumentException: Format specifier: 20K是为什么呢？

### ISSUE THREAD

**Issue by MUFCRyan** [lingochamp/FileDownloader#351]
Fatal Exception: java.util.MissingFormatArgumentException: Format specifier: 20K
       at java.util.Formatter.getArgument(Formatter.java:1111)
       at java.util.Formatter.doFormat(Formatter.java:1076)
       at java.util.Formatter.format(Formatter.java:1042)
       at java.util.Formatter.format(Formatter.java:1011)
       at java.lang.String.format(String.java:1999)
       at com.liulishuo.filedownloader.util.FileDownloadUtils.formatString(FileDownloadUtils.java:265)
       at com.liulishuo.filedownloader.util.FileDownloadLog.log(FileDownloadLog.java:69)
       at com.liulishuo.filedownloader.util.FileDownloadLog.log(FileDownloadLog.java:60)
       at com.liulishuo.filedownloader.util.FileDownloadLog.w(FileDownloadLog.java:52)
       at com.liulishuo.filedownloader.message.MessageSnapshotTaker.take(MessageSnapshotTaker.java:158)
       at com.liulishuo.filedownloader.services.FileDownloadRunnable.onStatusChanged(FileDownloadRunnable.java:711)
       at com.liulishuo.filedownloader.services.FileDownloadRunnable.onError(FileDownloadRunnable.java:643)
       at com.liulishuo.filedownloader.services.FileDownloadRunnable.loop(FileDownloadRunnable.java:338)
       at com.liulishuo.filedownloader.services.FileDownloadRunnable.run(FileDownloadRunnable.java:191)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by Jacksgong** [comment]
我这边没有遇到类似问题，可否告知下以下内容，以便于进一步定位问题:

1. 所使用FileDownloader的版本。
2. 所使用机型，与系统版本与型号。

**Comment by MUFCRyan** [comment]
之前忙，现在补一下，手机型号是SM-G9350，安卓版本是6.0.1，FileDownloader版本具体多少忘了，是九月初的那个，那个版本里当时下载文件是预先使用空文件占位的，之后的版本里应该加了相关设置

**Comment by Jacksgong** [comment]
> 那个版本里当时下载文件是预先使用空文件占位的，之后的版本里应该加了相关设置

恩。现在使用过程中问题还存在吗？

**Comment by MUFCRyan** [comment]
我其实没有碰到过，是集成的Crashlytics产生的Crash日志中出现的

**Comment by Jacksgong** [comment]
恩，我检查了下最新版本的`MessageSnapshotTaker`，应该是这块调用format相关的代码应该是没有问题的。我先将issue关闭，如果你在新版本中还有遇到，我再重新打开。
