### ISSUE TITLE
beforeExecute Exception

### ISSUE THREAD

**Issue by heming0512** [lingochamp/FileDownloader#366]
hello,some exceptions occure,can you help me ?
--------------------------------------------------------------------------------------------------
java.lang.OutOfMemoryError: Failed to allocate a 60 byte allocation with 4 free bytes and 4B until OOM
	at java.util.ArrayList.add(ArrayList.java:118)
	at java.util.regex.Splitter.split(Splitter.java:121)
	at java.util.regex.Pattern.split(Pattern.java:329)
	at java.lang.String.split(String.java:1658)
	at java.lang.String.split(String.java:1639)
	at com.liulishuo.filedownloader.c.b$a.beforeExecute(SourceFile:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1109)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by Jacksgong** [comment]
Could you please provide the Exception Stack Trace with non-Obfuscated?

and please give me the version of FileDownloader you are using, thanks.

**Comment by heming0512** [comment]
sorry,this Exception comes from umeng,  I didn't find it other informations,the version of FileDownloader is 1.0.1, if i find such as Exception next time,we will hava a discussion .

**Comment by Jacksgong** [comment]
Thanks for your response, This problem has already fixed in the latest version(1.2.2). 

> With the exception stack trace, this problem is raised, because we change the thread name with `String.split`.

**Comment by Jacksgong** [comment]
Ref [the code](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/util/FileDownloadExecutors.java#L64) in the latest version, we no longer change the thread name, when the thread has been created.
