### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by valmeeki001** [lingochamp/FileDownloader#378]
When try to **pause->resume->pause->resume** serially , i got this exception.  

```
E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                                                  java.lang.StackOverflowError
                                                                      at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:256)
                                                                      at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:386)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:118)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                      at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                      at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                      at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                      at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                      at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                      at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                      at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                      at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                      at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                  	at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecut
 W/dalvikvm: threadid=10: thread exiting with uncaught exception (group=0xa4ce5b38)

 FATAL EXCEPTION: Binder_2
                                                                      Process: com.test, PID: 1376
                                                                      java.lang.StackOverflowError
                                                                          at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:256)
                                                                          at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:386)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:118)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                          at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                          at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                          at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                          at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                          at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                          at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                          at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                          at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                          at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                          at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                          at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                          at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                          at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                          at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                          at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                          at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                          at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                          at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                          at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                          at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                          at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                          at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                          at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                          at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$Queue.putExceed(ExceedWait.java:129)
                                                                          at cn.dreamtobe.threadpool.ExceedWait$RejectedHandler.rejectedExecution(ExceedWait.java:42)
                                                                          at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
                                                                          at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1339)
                                                                          at cn.dreamtobe.threadpool.RealExecutors$ExceedWaitExecutor.execute(RealExecutors.java:59)
```

**Comment by Jacksgong** [comment]
This problem has been fixed since v1.1.5.

Ref: #321
