### ISSUE TITLE
报没有初始化的异常

### ISSUE THREAD

**Issue by Ayanokouji-Kenn** [lingochamp/FileDownloader#424]
` FileDownloader.init(getApplicationContext()); `有初始化，还是报异常
```java
  Process: com.aidebar.d8alarmclock:filedownloader, PID: 19655
               java.lang.ExceptionInInitializerError
                                                       at com.liulishuo.filedownloader.util.FileDownloadProperties$HolderClass.access$100(FileDownloadProperties.java:113)
                                                       at com.liulishuo.filedownloader.util.FileDownloadProperties.getImpl(FileDownloadProperties.java:118)
                                                       at com.liulishuo.filedownloader.services.FileDownloadService.onCreate(FileDownloadService.java:43)
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3280)
                                                       at android.app.ActivityThread.access$1900(ActivityThread.java:181)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:145)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6145)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
                                                    Caused by: java.lang.IllegalStateException: Please invoke the FileDownloader#init in Application#onCreate first.
                                                       at com.liulishuo.filedownloader.util.FileDownloadProperties.<init>(FileDownloadProperties.java:127)
                                                       at com.liulishuo.filedownloader.util.FileDownloadProperties.<init>(FileDownloadProperties.java:97)
                                                       at com.liulishuo.filedownloader.util.FileDownloadProperties$HolderClass.<clinit>(FileDownloadProperties.java:114)
                                                       at com.liulishuo.filedownloader.util.FileDownloadProperties$HolderClass.access$100(FileDownloadProperties.java:113) 
                                                       at com.liulishuo.filedownloader.util.FileDownloadProperties.getImpl(FileDownloadProperties.java:118) 
                                                       at com.liulishuo.filedownloader.services.FileDownloadService.onCreate(FileDownloadService.java:43) 
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3280) 
                                                       at android.app.ActivityThread.access$1900(ActivityThread.java:181) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1565) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:145) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6145) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) ```
LostServiceConnectedHandler执行到130行崩掉，追进去发现在BaseFileServiceUIGuard的第156行，bindService的时候崩

**Comment by Ayanokouji-Kenn** [comment]
问题解决，虽然还不明白为什么
在Application里为了防止remote service重复调用onCreate，导致一堆东西被重复初始化，我做了进程拦截
而这个似乎是新开进程，所以拿不到context？

**Comment by ElegantWang** [comment]
遇到同样问题，不需要单独进程参考[https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties](这里)

**Comment by Jacksgong** [comment]
@Ayanokouji-Kenn 嗯，是的。这边之所以要放到`Application#onCreate` 其中一个原因就是，这边需要下载进程初始化的时候，也可以持有下载进程的`applicationContext`。

我完善下这里的错误日志。

**Comment by Jacksgong** [comment]
这里确实是可以调整下，下载进程这边不再需要在`Application`启动的时候获取`Context`，可以直接在`FileDownloadService`启动时，通过`Service`取得对应的`ApplicationContext`

**Comment by Jacksgong** [comment]
需要在`FileDownloader#init`放到`Application'#onCreate`中进行初始化，具体原因，可以参看JAVA-DOC:

```java
/**
 * * Initialize the FileDownloader.
 * <p>
 * <strong>Note:</strong> This method just hold {@code context} and {@code maker}, so it is very
 * light(it is maybe need to spend 5ms for load some relate classes).
 * <p>
 * You need to invoke this method in {@link Application#onCreate()}, since the FileDownloadService
 * is running with the {@link android.app.Service#START_STICKY}, so it is just if you invoke this
 * this method in {@link Application#onCreate()}, FileDownloader can make sure the {@code maker}
 * can be assigned corrected each time when FileDownloadService is launching.
 *
 * @param context The context.
 * @param maker   Used to customize the download service, this value can be {@code null}.
 * @see #init(Context)
 */
public static void init(final Context context,
                        /**Nullable **/final DownloadMgrInitialParams.InitCustomMaker maker)
 ```
