### ISSUE TITLE
java.io.IOException: open failed: EINVAL (Invalid argument) at java.io.File.createNewFile(File.java:950) at com.liulishuo.filedownloader.services.FileDownloadRunnable.getOutputStream(FileDownloadRunnable.java:870) at com.liulishuo.filedownloader.services.FileDownloadRunnable.fetch(FileDownloadRunnable.java:423)

### ISSUE THREAD

**Issue by axuan2015** [lingochamp/FileDownloader#445]
下载出现这种错误:
java.io.IOException: open failed: EINVAL (Invalid argument)
at java.io.File.createNewFile(File.java:950)
at com.liulishuo.filedownloader.services.FileDownloadRunnable.getOutputStream(FileDownloadRunnable.java:870)
at com.liulishuo.filedownloader.services.FileDownloadRunnable.fetch(FileDownloadRunnable.java:423)

**Comment by Jacksgong** [comment]
这个是创建文件失败，根据[该ISSUE](http://stackoverflow.com/questions/11394616/java-io-ioexception-open-failed-einval-invalid-argument-when-saving-a-image) 这个很有可能是你提供的文件名有问题导致的。

根据调用栈，这里的异常抛到上层是正确的做法，因为里面无法决定该异常的处理策略。
