### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by axuan2015** [lingochamp/FileDownloader#446]
java.net.ProtocolException: unexpected end of stream
at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:380)
at okio.RealBufferedSource$1.read(RealBufferedSource.java:409)
at java.io.InputStream.read(InputStream.java:162)

**Comment by Jacksgong** [comment]
该问题与下载引擎无关，很有可能是网络节点问题，或者当前网络环境问题导致的。

> P.S: v1.3.9以及之后的版本已经支持定制化下载组件，如果有需要可以定制自己的下载组件。
