### ISSUE TITLE
FileDownloadHttpException: response code error: 401

### ISSUE THREAD

**Issue by axuan2015** [lingochamp/FileDownloader#448]
下载失败 错误日志如下:我想确切的知道是框架的问题 还是服务器的问题？
com.liulishuo.filedownloader.exception.FileDownloadHttpException: response code error: 401, 
request headers: Cache-Control: no-cache

response headers: Date: Wed, 11 Jan 2017 01:36:42 GMT
Server: nginx
Content-Type: application/json
Content-Length: 29
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: X-Log, X-Reqid
Access-Control-Max-Age: 2592000
X-Log: IO:1/401
X-Private: 1
X-Reqid: _loAADea_dDQk5gU
X-Via: 1.1 dwt36:2 (Cdn Cache Server V2.0), 1.1 taiwtong50:1 (Cdn Cache Server V2.0)
Connection: close

at com.liulishuo.filedownloader.services.FileDownloadRunnable.loop(FileDownloadRunnable.java:371)
at com.liulishuo.filedownloader.services.FileDownloadRunnable.run(FileDownloadRunnable.java:222)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

**Comment by Jacksgong** [comment]
Ref: https://httpstatuses.com/401

---

#### 与FileDownloader没有关系。

401-未经授权，如果你的服务器需要添加有关的头部来进行授权，你可以通过`BaseDownloadTask#addHeader`来添加相应的请求头参数。
