### ISSUE TITLE
App crashing when try to pause

### ISSUE THREAD

**Issue by danielnazareth** [lingochamp/FileDownloader#462]
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {MyApplication}: java.lang.NullPointerException: Attempt to invoke interface method 'com.liulishuo.filedownloader.BaseDownloadTask com.liulishuo.filedownloader.BaseDownloadTask$IRunningTask.getOrigin()' on a null object reference
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5066)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5089)
       at android.app.ActivityThread.access$1700(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1854)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'com.liulishuo.filedownloader.BaseDownloadTask com.liulishuo.filedownloader.BaseDownloadTask$IRunningTask.getOrigin()' on a null object reference
       at com.liulishuo.filedownloader.FileDownloadMessenger.process(FileDownloadMessenger.java:198)
       at com.liulishuo.filedownloader.FileDownloadMessenger.notifyPaused(FileDownloadMessenger.java:183)
       at com.liulishuo.filedownloader.FileDownloadList.remove(FileDownloadList.java:200)
       at com.liulishuo.filedownloader.DownloadTaskHunter.pause(DownloadTaskHunter.java:426)
       at com.liulishuo.filedownloader.DownloadTask.pause(DownloadTask.java:338)
       at com.liulishuo.filedownloader.FileDownloader.pauseAll(FileDownloader.java:229)
       at br.com.MyApplication.onActivityDestroyed(MyApplication.java:162)
       at android.app.Application.dispatchActivityDestroyed(Application.java:275)
       at android.app.Activity.onDestroy(Activity.java:1870)
       at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:386)
       at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:212)
       at br.com.MyApplication(MyActivity.java:217)
       at android.app.Activity.performDestroy(Activity.java:7102)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1170)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5044)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5089)
       at android.app.ActivityThread.access$1700(ActivityThread.java:222)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1854)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by Jacksgong** [comment]
#### Thanks for your feedback, but could you tell me the following information:

1.  Which version do you using?
2. How much frequency does this issue occurred and the rough situation about occurring this issue?

**Comment by danielnazareth** [comment]
Sure!

1. I'm using version 1.4.

2. Actually this crash has never occurred with me in development, but I'm using Fabric Crashlytics, and it shows that the crash happened 5 times in the last 5 days.

**Comment by Jacksgong** [comment]
Get, I will fix it.
