### ISSUE TITLE
Fatal Exception: java.util.MissingFormatArgumentException: Format specifier: 3D

### ISSUE THREAD

**Issue by javasoldiers** [lingochamp/FileDownloader#486]
Fatal Exception: java.util.MissingFormatArgumentException: Format specifier: 3D
       at java.util.Formatter.getArgument(Formatter.java:1109)
       at java.util.Formatter.doFormat(Formatter.java:1074)
       at java.util.Formatter.format(Formatter.java:1040)
       at java.util.Formatter.format(Formatter.java:1009)
       at java.lang.String.format(String.java:1992)
       at com.liulishuo.filedownloader.util.FileDownloadUtils.formatString(SourceFile:333)
       at com.liulishuo.filedownloader.util.FileDownloadLog.log(SourceFile:67)
       at com.liulishuo.filedownloader.util.FileDownloadLog.log(SourceFile:58)
       at com.liulishuo.filedownloader.util.FileDownloadLog.w(SourceFile:50)
       at com.liulishuo.filedownloader.message.MessageSnapshotTaker.take(SourceFile:177)
       at com.liulishuo.filedownloader.services.FileDownloadRunnable.onStatusChanged(SourceFile:827)
       at com.liulishuo.filedownloader.services.FileDownloadRunnable.onError(SourceFile:746)
       at com.liulishuo.filedownloader.services.FileDownloadRunnable.loop(SourceFile:402)
       at com.liulishuo.filedownloader.services.FileDownloadRunnable.run(SourceFile:222)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:838)

fileDownload版本是1.4.1

**Comment by Jacksgong** [comment]
多谢反馈，这个在问题1.5.x某个版本中已经修复了。目前使用最新的FileDownloader版本已经没有这个问题。
