### ISSUE TITLE
activity has leaked ServiceConnection 

### ISSUE THREAD

**Issue by myinnos** [lingochamp/FileDownloader#500]
```
activity has leaked ServiceConnection com.liulishuo.filedownloader.FileDownloadServiceUIGuard@27e0578 that was originally bound here
                                                                          at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1148)
                                                                          at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1042)
                                                                          at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1311)
                                                                          at android.app.ContextImpl.bindService(ContextImpl.java:1294)
                                                                          at android.content.ContextWrapper.bindService(ContextWrapper.java:604)
                                                                          at com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.bindStartByContext(BaseFileServiceUIGuard.java:156)
                                                                          at com.liulishuo.filedownloader.services.BaseFileServiceUIGuard.bindStartByContext(BaseFileServiceUIGuard.java:126)
                                                                          at com.liulishuo.filedownloader.FileDownloadServiceProxy.bindStartByContext(FileDownloadServiceProxy.java:122)
                                                                          at com.liulishuo.filedownloader.LostServiceConnectedHandler.dispatchTaskStart(LostServiceConnectedHandler.java:130)
                                                                          at com.liulishuo.filedownloader.DownloadTaskHunter.start(DownloadTaskHunter.java:571)
                                                                          at com.liulishuo.filedownloader.FileDownloadTaskLauncher$LaunchTaskRunnable.run(FileDownloadTaskLauncher.java:155)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
```

**Comment by Jacksgong** [comment]
Occur such issue because of you invoke `FileDownloader#init(Context, InitCustomMaker)` with the `context` of `Activity`,  so after you started download when activity is alive, the FileDownloadService would be bound to the `context` of the activity, and then when the activity is destroyed, the FileDownloadService isn't unbound.


---

Normally we recommended you invoke `FileDownloader#init` on the `Application#onCreate`because as the default configure the FileDownloadService is running on the separate process, so only you invoke it on the `Application#onCreate` we can touch the `InitCustomMaker` and `ApplicationContext`.

---

#### But for avoiding such things I will change codes

1. Using `context.getApplicationContext()`  on the `FileDownloader#init`
2. Change the mechanism of `FileDownloader#init`, and let user can setup FileDownloader anytime before using FileDownloader if user doesn't need to register components
