### ISSUE TITLE
java.util.MissingFormatArgumentException: Format specifier: 253D

### ISSUE THREAD

**Issue by oceanzhang01** [lingochamp/FileDownloader#524]
java.util.MissingFormatArgumentException: Format specifier: 253D
	at java.util.Formatter.getArgument(Formatter.java:1111)
	at java.util.Formatter.doFormat(Formatter.java:1076)
	at java.util.Formatter.format(Formatter.java:1042)
	at java.util.Formatter.format(Formatter.java:1011)
	at java.lang.String.format(String.java:2033)
	at com.liulishuo.filedownloader.util.FileDownloadUtils.formatString(FileDownloadUtils.java:333)
	at com.liulishuo.filedownloader.util.FileDownloadLog.log(FileDownloadLog.java:67)
	at com.liulishuo.filedownloader.util.FileDownloadLog.log(FileDownloadLog.java:58)
	at com.liulishuo.filedownloader.util.FileDownloadLog.w(FileDownloadLog.java:50)
	at com.liulishuo.filedownloader.message.MessageSnapshotTaker.take(MessageSnapshotTaker.java:177)
	at com.liulishuo.filedownloader.services.FileDownloadRunnable.onStatusChanged(FileDownloadRunnable.java:827)
	at com.liulishuo.filedownloader.services.FileDownloadRunnable.onError(FileDownloadRunnable.java:746)
	at com.liulishuo.filedownloader.services.FileDownloadRunnable.loop(FileDownloadRunnable.java:402)
	at com.liulishuo.filedownloader.services.FileDownloadRunnable.run(FileDownloadRunnable.java:222)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:848)

**Comment by Jacksgong** [comment]
This problem has been fixed on the 1.5.1. thanks for your raise this issue.

the commit: https://github.com/lingochamp/FileDownloader/commit/70c436d4dd8b99f4f44c0076b9b22f6744b76a31
