### ISSUE TITLE
Unable to create application

### ISSUE THREAD

**Issue by hwty824069** [lingochamp/FileDownloader#531]
版本1.4.2，下载任务的时候出现这个问题, 跟了下代码，在context.bindService(i, this, Context.BIND_AUTO_CREATE);出错
04-02 21:08:46.174 30228-30228/xxx:filedownloader E/EaseUI: enter the service process!
04-02 21:08:46.184 30228-30228/xxx:filedownloader E/dalvikvm: Could not find class 'org.greenrobot.greendao.database.DatabaseOpenHelper$EncryptedHelper', referenced from method org.greenrobot.greendao.database.DatabaseOpenHelper.checkEncryptedHelper
04-02 21:08:46.294 269-269/? E/SMD: DCD ON
04-02 21:08:46.314 30228-30228/xxx:filedownloader E/dalvikvm: Could not find class 'android.app.job.JobScheduler', referenced 

 method com.hyphenate.chat.EMClient.cancelJob
04-02 21:08:46.324 30228-30228/xxx:filedownloader E/dalvikvm: Could not find class 'com.hyphenate.chat.EMJobService', referenced from method com.hyphenate.chat.EMClient.scheduleJob
04-02 21:08:46.424 30228-30228/xxx:filedownloader E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: xxx:filedownloader, PID: 30228
                                                                                    java.lang.RuntimeException: Unable to create applicationxxx.meiyue.application.MeiYueApp: java.lang.NullPointerException
                                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4521)
                                                                                        at android.app.ActivityThread.access$1500(ActivityThread.java:157)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:157)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5293)
                                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                        at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by hwty824069** [comment]
04-02 21:28:18.224 20096-20096/xxx W/ContextImpl: Failed to ensure directory: /storage/extSdCard/Android/data/xxx/cache
04-02 21:28:18.234 20096-20096/xxx W/FileDownloader.DownloadServiceNotConnectedHelper: request get the status for the task[942588589] in the download service, but the download service isn't connected yet.
                                                                                                       You can use FileDownloader#isServiceConnected() to check whether the service has been connected, 
                                                                                                       besides you can use following functions easier to control your code invoke after the service has been connected: 
                                                                                                       1. FileDownloader#bindService(Runnable)
                                                                                                       2. FileDownloader#insureServiceBind()
                                                                                                       3. FileDownloader#insureServiceBindAsync()

**Comment by Jacksgong** [comment]
### 问题一： `java.lang.RuntimeException: Unable to create applicationxxx.meiyue.application.MeiYueApp: java.lang.NullPointerException`

#### 问题原因

这个问题是因为在filedownloader进程中被执行了你的相关代码导致的。

#### 具体原因

由于FileDownloadService默认是运行在filedownloader进程的，因此在filedownloader进程启动的时候会执行你的`Application#onCreate`，因此你在`Application#onCreate`中的所有逻辑将会被执行到，也是在这里触发了相关的问题。

#### 解决方案:

- 方案一: 通过在[filedownloader.properties](https://github.com/lingochamp/FileDownloader/wiki/filedownloader.properties)中配置`process.non-separate=true`让FileDownloadService运行在主进程，这样就不会有filedownloader进程了。
- 方案二: 在`Application#onCreate`中处理相关事务的时候判断下当前进程，如果是filedownloader进程，就只做`FileDownloader.init`不做其余任何逻辑。

### 问题二: `request get the status for the task[942588589] in the download service, but the download service isn't connected yet`

这个错误提示已经很明显了，由于所有的数据是在FileDownloadService中，因此需要确保下载服务是存在的才能获取的到，否则获取不到，这块的错误提示已经很清晰了:

```
You can use FileDownloader#isServiceConnected() to check whether the service has been connected,
besides you can use following functions easier to control your code invoke after the service has been connected:
1. FileDownloader#bindService(Runnable)
2. FileDownloader#insureServiceBind()
3. FileDownloader#insureServiceBindAsync()
```
