### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException Not a primitive field: com.liulishuo.filedownloader.b.b$a com.liulishuo.filedownloader.b.b.a com.liulishuo.filedownloader.message.SmallMessageSnapshot$ErrorMessageSnapshot.writeToParcel

### ISSUE THREAD

**Issue by sinhpn92** [lingochamp/FileDownloader#534]
I have got error from Crashlytics of Fabric:

```
Fatal Exception: java.lang.IllegalArgumentException: Not a primitive field: com.liulishuo.filedownloader.b.b$a com.liulishuo.filedownloader.b.b.a
       at java.lang.reflect.Field.getInt(Field.java)
       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:946)
       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
       at android.os.Parcel.writeSerializable(Parcel.java:1464)
       at com.liulishuo.filedownloader.message.SmallMessageSnapshot$ErrorMessageSnapshot.writeToParcel(SmallMessageSnapshot.java:289)
       at com.liulishuo.filedownloader.i.IFileDownloadIPCCallback$Stub$Proxy.callback(IFileDownloadIPCCallback.java:83)
       at com.liulishuo.filedownloader.services.FDServiceSeparateHandler.callback(FDServiceSeparateHandler.java:48)
       at com.liulishuo.filedownloader.services.FDServiceSeparateHandler.receive(FDServiceSeparateHandler.java:165)
       at com.liulishuo.filedownloader.message.MessageSnapshotThreadPool$FlowSingleExecutor$1.run(MessageSnapshotThreadPool.java:100)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

Do you know what's wrong here? Could you please review and check this issue? Thanks

**Comment by Jacksgong** [comment]
This problem is raised because of the process of FileDownloadService is crashed, finally I found the reason and fix it: https://github.com/lingochamp/FileDownloader/commit/70c436d4dd8b99f4f44c0076b9b22f6744b76a31
