### ISSUE TITLE
在某些Android盒子上出现了Failed to change locale for db '/data/data/xxx/databases/filedownloader.db' to 'zh_CN'.

### ISSUE THREAD

**Issue by lx5288** [lingochamp/FileDownloader#583]
java.lang.RuntimeException: Unable to create service com.liulishuo.filedownloader.services.FileDownloadService$SharedMainProcessService: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/xxxx/databases/filedownloader.db' to 'zh_CN'.
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2582)
	at android.app.ActivityThread.access$1800(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5030)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:649)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.da
这个错误频繁的出现在某个用户的盒子上，我们的错误日志上面有5000+条该错误
这个错误应该是在  db = openHelper.getWritableDatabase();时发生的
有人说把
myDatabase = SQLiteDatabase.openDatabase(myPath, null, SQLiteDatabase.OPEN_READWRITE);
改成
myDatabase = SQLiteDatabase.openDatabase(myPath, null, SQLiteDatabase.NO_LOCALIZED_COLLATORS | SQLiteDatabase.OPEN_READWRITE);
可以解决这个问题，但是由于盒子不是我们的我们无法复现该错误
不知道为什么，我们的全局异常捕获，重复的捕获了该问题，我们并没有重启应用，只是跳转到了错误页面

**Comment by lx5288** [comment]
下面还有个这个异常
android.database.sqlite.SQLiteFullException: database or disk is full
好像是磁盘空间满了的原因，但是我把磁盘空间填充，并没有出现这个异常

**Comment by lx5288** [comment]
详细信息
java.lang.RuntimeException: Unable to create service com.liulishuo.filedownloader.services.FileDownloadService$SharedMainProcessService: android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2582)
	at android.app.ActivityThread.access$1800(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5030)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:649)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteFullException: database or disk is ful
还有另外一个数据库错误
java.lang.RuntimeException: Unable to create service com.liulishuo.filedownloader.services.FileDownloadService$SharedMainProcessService: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:2582)
	at android.app.ActivityThread.access$1800(ActivityThread.java:135)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5039)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:844)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteCantOpenData

**Comment by Jacksgong** [comment]
其实数据库在很多方面是有很多长尾问题的，如(code `13`)磁盘已满、(code `1546`|`3850`|`778`|`2570`|`1034`|`10`|`unkown`)I/O错误、(code `0`|`14`)打开失败、(sqlite code `14`)权限问题、(code `1032`)只读问题等等等等。

而数据库只是FileDownloader需要用到的其中一个组件，所以FileDownloader中通过Android默认的Sqlite，按照官方接口实现了一个默认的简单的Sqlite组件用于存储。

因此：这类小概率长尾问题，一旦遇到FileDownloader会回调`error`到前台让你获知，而如果你的应用中本身就有处理各类的数据库长尾异常或者你们本身使用Realm或者是NoSQL的数据库，完全是可以通过 定制自己数据库组件的接口 注册到FileDownloader中的: [组件定制](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)
