### ISSUE TITLE
1.5.0 版本 初始化报错

### ISSUE THREAD

**Issue by UBNTRogerLuo** [lingochamp/FileDownloader#593]
使用 FileDownloader.init(this);

Caused by: java.lang.NullPointerException: Attempt to invoke direct method 'void com.liulishuo.filedownloader.services.DownloadMgrInitialParams$InitCustomMaker.securityCheck()' on a null object reference
                                                       at com.liulishuo.filedownloader.services.DownloadMgrInitialParams$InitCustomMaker.access$000(DownloadMgrInitialParams.java:155)
                                                       at com.liulishuo.filedownloader.services.DownloadMgrInitialParams.<init>(DownloadMgrInitialParams.java:42)
                                                       at com.liulishuo.filedownloader.download.CustomComponentHolder.setInitCustomMaker(CustomComponentHolder.java:50)
                                                       at com.liulishuo.filedownloader.FileDownloader.init(FileDownloader.java:82)
                                                       at com.liulishuo.filedownloader.FileDownloader.init(FileDownloader.java:55)
                                                       at com.ubnt.fr.services.App.onCreate(App.java:52)

**Comment by Jacksgong** [comment]
多谢多谢，一会儿版本带上。#592
