### ISSUE TITLE
SQLiteCantOpenDatabaseException

### ISSUE THREAD

**Issue by Quennel** [lingochamp/FileDownloader#595]
配置为process.non-separate=true情况下，出现数据库调用出错的问题。且出现此错误的数量不少，设备不限定在特定机型。

crash log:
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)
#################################################################
Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
Caused By : Application has opened two many files. Maximum of available file descriptors in one process is 1024 in default.
	(unable to open database file (code 2062))
#################################################################
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:813)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1878)
       at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1824)
       at com.liulishuo.filedownloader.services.DefaultDatabaseImpl.update(SourceFile:346)
       at com.liulishuo.filedownloader.services.DefaultDatabaseImpl.updateError(SourceFile:292)
       at com.liulishuo.filedownloader.services.FileDownloadRunnable.onError(SourceFile:767)
       at com.liulishuo.filedownloader.services.FileDownloadRunnable.loop(SourceFile:434)
       at com.liulishuo.filedownloader.services.FileDownloadRunnable.run(SourceFile:226)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

**Comment by Jacksgong** [comment]
这个应该与`process.non-separate=true`无关，该参数只是下载服务是否运行在独立进程，对于数据库的使用无论运行在哪个进程并没有特殊处理，并且在流利说内部的下载也是使用`process.non-separate=true`该配置的。

----

具体问题应该是`Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)` 而根据原因描述: `Application has opened two many files. Maximum of available file descriptors in one process is 1024 in default.`，

### 也就是说应用持有的文件描述符过多（默认情况下一个进程只允许持有1024个文件描述符）。

## 因此: 

你看看你代码当中是否存在持有文件描述符并没有close的情况。 也给一下你所使用的FileDownloader的版本，我再检查下代码中所有文件描述符是否有被close，默认情况下除去数据库文件的那个，默认的同步任务数是3 * 最新版本默认单任务可以同时最多5个写入 = 15个描述符，应该是远低于1024才对。

**Comment by Jacksgong** [comment]
其实数据库在很多方面是有很多长尾问题的，如(code `13`)磁盘已满、(code `1546`|`3850`|`778`|`2570`|`1034`|`10`|`unkown`)I/O错误、(code `0`|`14`)打开失败、(sqlite code `14`)权限问题、(code `1032`)只读问题等等等等。

而数据库只是FileDownloader需要用到的其中一个组件，所以FileDownloader中通过Android默认的Sqlite，按照官方接口实现了一个默认的简单的Sqlite组件用于存储。

因此：这类小概率长尾问题，一旦遇到FileDownloader会回调`error`到前台让你获知，而如果你的应用中本身就有处理各类的数据库长尾异常或者你们本身使用Realm或者是NoSQL的数据库，完全是可以通过 定制自己数据库组件的接口 注册到FileDownloader中的: [组件定制](https://github.com/lingochamp/FileDownloader/wiki/Customizable-Component)

**Comment by Quennel** [comment]
谢谢，已通过自定义数据库组件解决。

**Comment by Jacksgong** [comment]
@Quennel 赞，可否告知下你具体的解决方案呢？

**Comment by Quennel** [comment]
@Jacksgong 只是在自定义数据库组件中加入异常情况的处理，因为项目内涉及数据库和文件操作的还有第三方闭源SDK，所以并不好排查。

**Comment by Jacksgong** [comment]
@Quennel Okay.明白。
