### ISSUE TITLE
更新v1.5.1版本之后，出现NullPointerException

### ISSUE THREAD

**Issue by Quennel** [lingochamp/FileDownloader#598]
更新v1.5.1版本后，分别出现以下NullPointerException，这几个在使用v1.4.2版本时均未统计到，其中第一个出现次数较多。

========crash log 1=========
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'long com.liulishuo.filedownloader.download.e.a' on a null object reference
       at com.liulishuo.filedownloader.download.DownloadRunnable.run(SourceFile:102)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

========crash log 2=========
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.liulishuo.filedownloader.services.g.a(int, int, long)' on a null object reference
       at com.liulishuo.filedownloader.download.FetchDataTask.sync(SourceFile:202)
       at com.liulishuo.filedownloader.download.FetchDataTask.pause(SourceFile:58)
       at com.liulishuo.filedownloader.download.DownloadRunnable.pause(SourceFile:58)
       at com.liulishuo.filedownloader.download.DownloadRunnable.discard(SourceFile:62)
       at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.onError(SourceFile:623)
       at com.liulishuo.filedownloader.download.DownloadRunnable.run(SourceFile:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

========crash log 3=========
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.liulishuo.filedownloader.download.c.a()' on a null object reference
       at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.pause(SourceFile:134)
       at com.liulishuo.filedownloader.services.FileDownloadThreadPool.cancel(SourceFile:95)
       at com.liulishuo.filedownloader.services.FileDownloadManager.pause(SourceFile:200)
       at com.liulishuo.filedownloader.services.FDServiceSharedHandler.pause(SourceFile:66)
       at com.liulishuo.filedownloader.FileDownloadServiceSharedTransmit.pause(SourceFile:65)
       at com.liulishuo.filedownloader.FileDownloadServiceProxy.pause(SourceFile:72)
       at com.liulishuo.filedownloader.DownloadTaskHunter.pause(SourceFile:419)
       at com.liulishuo.filedownloader.DownloadTask.pause(SourceFile:338)
       at com.liulishuo.filedownloader.FileDownloader.pauseAll(SourceFile:227)
       at media.itsme.common.download.FileDownloadHelper.pauseAllDownload(SourceFile:221)
       at media.itsme.common.utils.LoginHelper.logout(SourceFile:928)
       at media.itsme.common.activity.setting.UserSettingActivity.logout(SourceFile:245)
       at media.itsme.common.activity.setting.UserSettingActivity.onClick(SourceFile:142)
       at android.view.View.performClick(View.java:5212)
       at android.view.View$PerformClick.run(View.java:21214)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5628)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:850)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:734)

**Comment by Jacksgong** [comment]
感谢提出，今晚会发布小版本修复这些问题。

**Comment by Jacksgong** [comment]
如若还有其他问题，欢迎直接提出，谢谢哈。

**Comment by Quennel** [comment]
@Jacksgong 👍响应速度666

**Comment by Jacksgong** [comment]
@Quennel 1.5.0下载那层代码重构比较大，我自己虽然有各种测试，但是场景不够多，担心影响你们线上，所以不得不快速跟进。

**Comment by Jacksgong** [comment]
已经在1.5.2版本带上: [迭代日志](https://github.com/lingochamp/FileDownloader/blob/master/CHANGELOG-ZH.md)
