### ISSUE TITLE
Crash at com.liulishuo.filedownloader.download.FetchDataTask.sync

### ISSUE THREAD

**Issue by sinhpn92** [lingochamp/FileDownloader#609]
I got error in my logs: 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.liulishuo.filedownloader.i.a.a()' on a null object reference
       at com.liulishuo.filedownloader.download.FetchDataTask.sync(FetchDataTask.java:194)
       at com.liulishuo.filedownloader.download.FetchDataTask.pause(FetchDataTask.java:58)
       at com.liulishuo.filedownloader.download.DownloadRunnable.pause(DownloadRunnable.java:58)
       at com.liulishuo.filedownloader.download.DownloadRunnable.discard(DownloadRunnable.java:62)
       at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.onError(DownloadLaunchRunnable.java:623)
       at com.liulishuo.filedownloader.download.DownloadRunnable.run(DownloadRunnable.java:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

And:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.liulishuo.filedownloader.i.a.a()' on a null object reference
       at com.liulishuo.filedownloader.download.FetchDataTask.sync(FetchDataTask.java:194)
       at com.liulishuo.filedownloader.download.FetchDataTask.pause(FetchDataTask.java:58)
       at com.liulishuo.filedownloader.download.DownloadRunnable.pause(DownloadRunnable.java:58)
       at com.liulishuo.filedownloader.download.DownloadRunnable.discard(DownloadRunnable.java:62)
       at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.onError(DownloadLaunchRunnable.java:623)
       at com.liulishuo.filedownloader.download.DownloadRunnable.run(DownloadRunnable.java:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```
My version: 1.5.5
What's wrong here? Could u please check?

**Comment by Jacksgong** [comment]
#### the two error stack seems the same one. And the bug has been fixed seems `v1.5.3`

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'void com.liulishuo.filedownloader.i.a.a()' on a null object reference
       at com.liulishuo.filedownloader.download.FetchDataTask.sync(FetchDataTask.java:194)
       at com.liulishuo.filedownloader.download.FetchDataTask.pause(FetchDataTask.java:58)
       at com.liulishuo.filedownloader.download.DownloadRunnable.pause(DownloadRunnable.java:58)
       at com.liulishuo.filedownloader.download.DownloadRunnable.discard(DownloadRunnable.java:62)
       at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.onError(DownloadLaunchRunnable.java:623)
       at com.liulishuo.filedownloader.download.DownloadRunnable.run(DownloadRunnable.java:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

with the stack tree: `FetchDataTask.sync(FetchDataTask.java:194)`, it match on `v1.5.1`, which has been fixed since `v1.5.3` with [the commit](https://github.com/lingochamp/FileDownloader/commit/0521c58492e0b225380385d658518d83e30e1679).

**Comment by Jacksgong** [comment]
Ref : https://github.com/lingochamp/FileDownloader/issues/601#issuecomment-307053815

**Comment by Jacksgong** [comment]
with the stack: 

```
       # outputStream is null
       at com.liulishuo.filedownloader.download.FetchDataTask.sync(FetchDataTask.java:194)
        # pause
       at com.liulishuo.filedownloader.download.FetchDataTask.pause(FetchDataTask.java:58)
```

- all problem is occured when the user invoke `pause`.
- and the `outputStream` null only if the FetchDataTask still not launch

so the [the fix commit](https://github.com/lingochamp/FileDownloader/commit/0521c58492e0b225380385d658518d83e30e1679) on `v1.5.3` can fix the problem through checking whether the `ouputStream` is  `null` before invoking `sync` method.

**Comment by Jacksgong** [comment]
You also can check the releas note on here: https://github.com/lingochamp/FileDownloader/releases/tag/v1.5.3
