### ISSUE TITLE
IllegalStateException database / CursorWindow

### ISSUE THREAD

**Issue by HugoGresse** [lingochamp/FileDownloader#610]
I've encounterd this issue on a Nexus 5 runing 6.0.1 : 

`Caused by java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.`

FileDownloader v1.5.5

See full crash [here](http://crashes.to/s/e972fe81d0f). 

It will really help if you can look into it.

**Comment by YuriHeupa** [comment]
I'm also facing the same issue. There's already 483 crash occurrences among different devices and operating system versions. See [here](http://crashes.to/s/d4c752f4184).

**Comment by Jacksgong** [comment]
It's very weird, the column must exist but the cursor can't found.

@HugoGresse In your exception stack:

```
com.liulishuo.filedownloader.services.DefaultDatabaseImpl$MaintainerIterator.next (DefaultDatabaseImpl.java:322)
```
It point to can not found `pathAsDirectory` column through `cursor#getColumnIndex`, but this column is added since database version 2:

```java
@Override
public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    if (oldVersion < 2) {
        String addAsDirectoryColumn = "ALTER TABLE " + DefaultDatabaseImpl.TABLE_NAME +
                " ADD COLUMN " + FileDownloadModel.PATH_AS_DIRECTORY +
                " TINYINT(1) DEFAULT 0";
        db.execSQL(addAsDirectoryColumn);

        String addFilenameColumn = "ALTER TABLE " + DefaultDatabaseImpl.TABLE_NAME +
                " ADD COLUMN " + FileDownloadModel.FILENAME +
                " VARCHAR";
        db.execSQL(addFilenameColumn);
    }
    ...
}
```

@YuriHeupa the stack you provided I cannot match any code on line `1329`:

```
com.liulishuo.filedownloader.services.DefaultDatabaseImpl$MaintainerIterator.next (DefaultDatabaseImpl.java:1329)
```

so, could you please provide some other stack, help me find the regular on this problem?

---

And could you two guys fix such problem with me, it would be nice if you can help me with this problem, and PR.

#### And following are related methods

1.  Create and Upgrade database: `DefaultDatabaseOpenHelper#onUpgrade`、`DefaultDatabaseOpenHelper#onCreate`
2. Problem site: `DefaultDatabaseImpl.MaintainerIterator#next`, two exception stack points to we get column index is -1(which means can't find) on `cursor#getColumnIndex`.
3.  `CustomComponentHolder#maintainDatabase` which using `DefaultDatabaseImpl.MaintainerIterator` to restore data from the database

**Comment by sinhpn92** [comment]
I have problem too. My log: 
```
Fatal Exception: java.lang.RuntimeException: Unable to create service com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService: java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3883)
       at android.app.ActivityThread.access$2100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1909)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.IllegalStateException: Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetLong(CursorWindow.java)
       at android.database.CursorWindow.getLong(CursorWindow.java:524)
       at android.database.CursorWindow.getInt(CursorWindow.java:591)
       at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:69)
       at com.liulishuo.filedownloader.services.DefaultDatabaseImpl$MaintainerIterator.next(DefaultDatabaseImpl.java:329)
       at com.liulishuo.filedownloader.services.DefaultDatabaseImpl$MaintainerIterator.next(DefaultDatabaseImpl.java:302)
       at com.liulishuo.filedownloader.download.CustomComponentHolder.maintainDatabase(CustomComponentHolder.java:163)
       at com.liulishuo.filedownloader.download.CustomComponentHolder.getDatabaseInstance(CustomComponentHolder.java:90)
       at com.liulishuo.filedownloader.services.FileDownloadManager.(FileDownloadManager.java)
       at com.liulishuo.filedownloader.services.FileDownloadService.onCreate(FileDownloadService.java:52)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3873)
       at android.app.ActivityThread.access$2100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1909)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by Jacksgong** [comment]
#### Finally I find the Reason of the crash:

Executions are invoked for SQLite isn't effective immediately on `DefaultDatabaseOpenHelper #onUpgrade` method, because of we enable the WAL(Write-Ahead-Logging) for SQLite since `v1.5.2`.

So after database upgrade, we expect everything is changed on the database but NOT............... so some column can't find...

#### When does your user can face this crash?

The following condition must be met at the same time:

1. Your user upgrades the filedownloader from `v1.4.3` or older version jump to the `v1.5.2` or newer version directly(because WAL is enabled since v1.5.2)
2. Your user used filedownloader to download something( So the database has been created )
3. There are something downloaded tasks are paused on breakpoint and stored on the database( So we would invoke `maintainDatabase` method )

#### THIS ISSUE WILL BE FIXED ON `1.5.6`

**Comment by HugoGresse** [comment]
Wooo that was a really complicated issue :/ Thanks for working on it!

**Comment by sinhpn92** [comment]
Thanks so much

**Comment by YuriHeupa** [comment]
Sorry for the late response.. and thanks for looking into this, really appreciated!!

**Comment by HugoGresse** [comment]
did you guyes are able to use the 1.5.6 @sinhpn92 @YuriHeupa Androdi Studio is unable to import the classes :/

**Comment by YuriHeupa** [comment]
@HugoGresse Yeh, I did. Try cleaning then rebuilding the project.

**Comment by HugoGresse** [comment]
Yep I did, somehting got wrong with AS see #620
