### ISSUE TITLE
FileDownloadSerialQueue中的任务pause后如何恢复

### ISSUE THREAD

**Issue by AllenMeex** [lingochamp/FileDownloader#614]
新建一个FileDownloadSerialQueue，并且enqueue()一个task，task开始下载，然后调用task.pause()暂停task，请问这时候如何恢复task，我试了task.start()和重新将这个task enqueue，都崩溃了：

`java.lang.IllegalStateException: This task is dirty to restart, If you want to reuse this task, please invoke #reuse method manually and retry to restart again.com.liulishuo.filedownloader.DownloadTaskHunter@4283fa10
                                                                               at com.liulishuo.filedownloader.DownloadTask.startTaskUnchecked(DownloadTask.java:318)
                                                                               at com.liulishuo.filedownloader.DownloadTask.start(DownloadTask.java:305)`

提示使用 reuse()，我在task.start()前加了reuse()确实可以继续了，但队列变成并行了。。此时我再enqueue()另外一个task，两个task同时进行了

请问如何解决这个问题？ 多谢指导~

**Comment by Jacksgong** [comment]
> FileDownloadSerialQueue中的任务pause后如何恢复

暂停: `task.pause` ->  复用: `task.reuse` -> 重新进入串行队列: `enqueue()`

---

P.S. 任何task调用自己的`start`都是全局并行启动，而丢到`FileDownloadSerialQueue`中，就是让其来管理什么时候调用它的`start`来使得任务变成串行执行。
