### ISSUE TITLE
HM NOTE 1TD   Android OS：4.2.2

### ISSUE THREAD

**Issue by lcj0304** [lingochamp/FileDownloader#639]
java.util.MissingFormatArgumentException: Format specifier: 20i
	at java.util.Formatter.getArgument(Formatter.java:1109)
	at java.util.Formatter.doFormat(Formatter.java:1074)
	at java.util.Formatter.format(Formatter.java:1040)
	at java.util.Formatter.format(Formatter.java:1009)
	at java.lang.String.format(String.java:1992)
	at com.liulishuo.filedownloader.util.FileDownloadUtils.formatString(FileDownloadUtils.java:286)
	at com.liulishuo.filedownloader.util.FileDownloadLog.log(FileDownloadLog.java:69)
	at com.liulishuo.filedownloader.util.FileDownloadLog.log(FileDownloadLog.java:60)
	at com.liulishuo.filedownloader.util.FileDownloadLog.w(FileDownloadLog.java:52)
	at com.liulishuo.filedownloader.message.MessageSnapshotTaker.take(MessageSnapshotTaker.java:157)
	at com.liulishuo.filedownloader.message.MessageSnapshotTaker.take(MessageSnapshotTaker.java:39)
	at com.liulishuo.filedownloader.services.FileDownloadRunnable.onStatusChanged(FileDownloadRunnable.java:634)
	at com.liulishuo.filedownloader.services.FileDownloadRunnable.onError(FileDownloadRunnable.java:566)
	at com.liulishuo.filedownloader.services.FileDownloadRunnable.loop(FileDownloadRunnable.java:332)
	at com.liulishuo.filedownloader.services.FileDownloadRunnable.run(FileDownloadRunnable.java:184)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)

代码改一下吧。

**Comment by lcj0304** [comment]
defaultConfig {
        minSdkVersion 8
        targetSdkVersion 21
        versionCode 22
        versionName "0.3.1"
    }

**Comment by Jacksgong** [comment]
This problem has been fixed on the 1.5.1. thanks for your raise this issue.

the commit: https://github.com/lingochamp/FileDownloader/commit/70c436d4dd8b99f4f44c0076b9b22f6744b76a31
