### ISSUE TITLE
java.io.IOException: offset < 0 when trying to download a file of 4GB in size 

### ISSUE THREAD

**Issue by SapneshNaik** [lingochamp/FileDownloader#669]
```
java.io.IOException: offset < 0: -791045736
W/System.err:     at java.io.RandomAccessFile.seek(RandomAccessFile.java:542)
W/System.err:     at com.liulishuo.filedownloader.stream.FileDownloadRandomAccessFile.seek(FileDownloadRandomAccessFile.java:54)
W/System.err:     at com.liulishuo.filedownloader.download.FetchDataTask.run(FetchDataTask.java:113)
W/System.err:     at com.liulishuo.filedownloader.download.DownloadRunnable.run(DownloadRunnable.java:113)
 W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err:     at java.lang.Thread.run(Thread.java:762)
```

What might be causing this ?

I am using a modified version of the example show in demo, with FileDownloadLageFileListener.
```
        return FileDownloader.getImpl().create(url)
                .setPath(path, false)
                .setCallbackProgressTimes(300)
                .setMinIntervalUpdateSpeed(400)
                .setTag(tag)
                .setListener(new FileDownloadLargeFileListener() {

                    @Override
                    protected void pending(BaseDownloadTask task, long soFarBytes, long totalBytes) {
//                        super.pending(task, soFarBytes, totalBytes);
                        ((ViewHolder) task.getTag()).updatePending(task);
                    }

                    @Override
                    protected void progress(BaseDownloadTask task, long soFarBytes, long totalBytes) {
//                        super.progress(task, soFarBytes, totalBytes);
//                        super.lon
                        ((ViewHolder) task.getTag()).updateProgress(soFarBytes, totalBytes,
                                task.getSpeed());
                    }

                    @Override
                    protected void error(BaseDownloadTask task, Throwable e) {
//                        super.error(task, e);
                        ((ViewHolder) task.getTag()).updateError(e, task.getSpeed());
                    }

                    @Override
                    protected void connected(BaseDownloadTask task, String etag, boolean isContinue, long soFarBytes, long totalBytes) {
//                        super.connected(task, etag, isContinue, soFarBytes, totalBytes);
                        ((ViewHolder) task.getTag()).updateConnected(etag, task.getFilename());
                    }

                    @Override
                    protected void paused(BaseDownloadTask task, long soFarBytes, long totalBytes) {
//                        super.paused(task, soFarBytes, totalBytes);
                        ((ViewHolder) task.getTag()).updatePaused(task.getSpeed());
                    }

                    @Override
                    protected void completed(BaseDownloadTask task) {
//                        super.completed(task);
                        ((ViewHolder) task.getTag()).updateCompleted(task);
                    }

                    @Override
                    protected void warn(BaseDownloadTask task) {
//                        super.warn(task);
                        ((ViewHolder) task.getTag()).updateWarn();
                    }
                });

```

**Comment by Jacksgong** [comment]
This would be reproduced when FileDownloader resumes the downloading from the break point larger than 1.99G.

---

Now, you can fetch the latest commit on master and please run the demo again to ensure whether it has been fixed.

**Comment by SapneshNaik** [comment]
Thank you. but how do I fetch the latest commit into my project? I'm using version 1.6.1 which I added using gradle

**Comment by Jacksgong** [comment]
Do be worry, this commit would be release on tomorrow evening with version 1.6.2.
