### ISSUE TITLE
单文件下载暂停后无法继续the messenger is working, can't re-appointment 咋回事?

### ISSUE THREAD

**Issue by EnglandZhang** [lingochamp/FileDownloader#671]
java.lang.IllegalStateException: the messenger is working, can't re-appointment for 9004235@com.liulishuo.filedownloader.DownloadTask@4a8a8b

**Comment by rantianhua** [comment]
请提供你的调用方式，在什么情况下使用 `resuse` 方法，完整的日志也请提供一下。

**Comment by rantianhua** [comment]
长时间未回复。

**Comment by yang0000meng** [comment]
我也遇到相同的问题
java.lang.IllegalStateException: the messenger is working, can't re-appointment for 1556230016@com.liulishuo.filedownloader.DownloadTask@f67b96c
	at com.liulishuo.filedownloader.FileDownloadMessenger.reAppointment(FileDownloadMessenger.java:380)
	at com.liulishuo.filedownloader.DownloadTaskHunter.reset(DownloadTaskHunter.java:455)
	at com.liulishuo.filedownloader.DownloadTask.reuse(DownloadTask.java:260)
	at com.liulishuo.filedownloader.FileDownloadQueueSet.reuseAndStart(FileDownloadQueueSet.java:106)
	at com.luren.videocollect.ui.main.down.TasksManager.down(TasksManager.java:510)
	at com.luren.videocollect.ui.main.down.TasksManager$3.onSuccess(TasksManager.java:680)
	at com.luren.videocollect.ui.main.down.TasksManager$3.onSuccess(TasksManager.java:637)
	at com.luren.videocollect.utils.http.nohttp.HttpResponseAllListener.onSucceed(HttpResponseAllListener.java:97)
	at com.yanzhenjie.nohttp.rest.Messenger$Poster.run(Messenger.java:92)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
