### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'com.liulishuo.filedownloader.a com.liulishuo.filedownloader.a$b.P()' on a null object reference

### ISSUE THREAD

**Issue by Godsbox** [lingochamp/FileDownloader#680]
java.lang.NullPointerException: Attempt to invoke interface method 'com.liulishuo.filedownloader.a com.liulishuo.filedownloader.a$b.P()' on a null object reference
	at com.liulishuo.filedownloader.FileDownloadMessenger.toString(FileDownloadMessenger.java:395)
	at java.lang.StringBuilder.append(StringBuilder.java:202)
	at android.os.Message.toString(Message.java:522)
	at android.os.Message.toString(Message.java:493)
	at java.lang.StringBuilder.append(StringBuilder.java:202)
	at android.os.Looper.loop(Looper.java:195)
	at android.app.ActivityThread.main(ActivityThread.java:5619)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:976)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)

**Comment by Godsbox** [comment]
it's why ?

**Comment by weikano** [comment]
Still has this problem in version 1.7.5
