### ISSUE TITLE
wifi切换移动网络后奔溃

### ISSUE THREAD

**Issue by aii1991** [lingochamp/FileDownloader#684]
### 测试手机
中兴c880s
### 主要代码
```java
  FileDownloadQueueSet queueSet = new FileDownloadQueueSet(mFileDownloadListener);
        queueSet.setAutoRetryTimes(1);
        queueSet.setDirectory(FileUtil.getCacheDownloadFileDir(this).getAbsolutePath());
        queueSet.downloadSequentially(tasks);
        queueSet.setWifiRequired(true); //此处引起的异常，没有走error回调
        queueSet.start();
```
### 异常信息
```
FATAL EXCEPTION: FileDownloader-Network1
                                                                                  Process: com.talenton.dwjx:filedownloader, PID: 16029
                                                                                  com.liulishuo.filedownloader.exception.FileDownloadNetworkPolicyException: Only allows downloading this task on the wifi network type
                                                                                      at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.checkupBeforeConnect(DownloadLaunchRunnable.java:660)
                                                                                      at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:209)
                                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                      at java.lang.Thread.run(Thread.java:818)
```

### 疑问
后台下载进程的异常要如何捕获

**Comment by Jacksgong** [comment]
该问题是1.5.0引入，在[1.5.6](https://github.com/lingochamp/FileDownloader/releases/tag/v1.5.6)中得到修复，建议使用最新版本。
