### ISSUE TITLE
Error: Not a primitive field: java.util.Map com.liulishuo.filedownloader.d.b.a

### ISSUE THREAD

**Issue by sinhpn92** [lingochamp/FileDownloader#695]
I have got an error in my report:
```
Fatal Exception: java.lang.IllegalArgumentException: Not a primitive field: java.util.Map com.liulishuo.filedownloader.d.b.a
       at java.lang.reflect.Field.getInt(Field.java)
       at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:946)
       at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
       at android.os.Parcel.writeSerializable(Parcel.java:1463)
       at com.liulishuo.filedownloader.message.SmallMessageSnapshot$ErrorMessageSnapshot.writeToParcel(SmallMessageSnapshot.java:289)
       at com.liulishuo.filedownloader.i.IFileDownloadIPCCallback$Stub$Proxy.callback(IFileDownloadIPCCallback.java:83)
       at com.liulishuo.filedownloader.services.FDServiceSeparateHandler.callback(FDServiceSeparateHandler.java:48)
       at com.liulishuo.filedownloader.services.FDServiceSeparateHandler.receive(FDServiceSeparateHandler.java:165)
       at com.liulishuo.filedownloader.message.MessageSnapshotThreadPool$FlowSingleExecutor$1.run(MessageSnapshotThreadPool.java:100)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

What's wrong here? Did it fix? Could u please review?

**Comment by Jacksgong** [comment]
could u please de-obfuscate `com.liulishuo.filedownloader.d.b.a` because it's very odd, only one place using `java.util.Map` is `FileDownloadHttpException` which has already convert to the `Serializable` with `HashMap`.

**Comment by sinhpn92** [comment]
@Jacksgong : Oh this my error in my Crashlytish report and I don't know how to make this error again. This error in version `1.6.0`. Thanks
