### ISSUE TITLE
创建任务后出错退出

### ISSUE THREAD

**Issue by kyly1982** [lingochamp/FileDownloader#72]
我是用的单线程下载，一开始就会出错。
FATAL EXCEPTION: main
                                                   Process: com.mckuai.imc:filedownloader, PID: 13796
                                                   java.lang.RuntimeException: Unable to create service com.liulishuo.filedownloader.services.FileDownloadService: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.sqlite.SQLiteDatabase android.content.Context.openOrCreateDatabase(java.lang.String, int, android.database.sqlite.SQLiteDatabase$CursorFactory, android.database.DatabaseErrorHandler)' on a null object reference
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2804)
                                                       at android.app.ActivityThread.access$1900(ActivityThread.java:154)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.sqlite.SQLiteDatabase android.content.Context.openOrCreateDatabase(java.lang.String, int, android.database.sqlite.SQLiteDatabase$CursorFactory, android.database.DatabaseErrorHandler)' on a null object reference
                                                       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                                                       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                       at com.liulishuo.filedownloader.services.FileDownloadDBHelper.<init>(FileDownloadDBHelper.java:49)
                                                       at com.liulishuo.filedownloader.services.FileDownloadMgr.<init>(FileDownloadMgr.java:46)
                                                       at com.liulishuo.filedownloader.services.FileDownloadService$FileDownloadServiceBinder.<init>(FileDownloadService.java:81)
                                                       at com.liulishuo.filedownloader.services.FileDownloadService$FileDownloadServiceBinder.<init>(FileDownloadService.java:75)
                                                       at com.liulishuo.filedownloader.services.FileDownloadService.createBinder(FileDownloadService.java:57)
                                                       at com.liulishuo.filedownloader.services.FileDownloadService.createBinder(FileDownloadService.java:36)
                                                       at com.liulishuo.filedownloader.services.BaseFileService.onCreate(BaseFileService.java:66)
                                                       at com.liulishuo.filedownloader.services.FileDownloadService.onCreate(FileDownloadService.java:42)
                                                       at android.app.ActivityThread.handleCreateService(ActivityThread.java:2794)
                                                       at android.app.ActivityThread.access$1900(ActivityThread.java:154) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1404) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by Jacksgong** [comment]
你看下是否没有在Application的onCreate中进行初始化，因为下载进程需要在这里缓存Application Context.
