### ISSUE TITLE
下载服务出现错误无限重启问题

### ISSUE THREAD

**Issue by lx5288** [lingochamp/FileDownloader#727]
初始化下载的时候数据库报错了，然后我捕获了全局异常，结果导致无限弹出异常页面！
我们的应用是安装在system/app目录下的应用，经常报下面这个异常！

**Comment by lx5288** [comment]
java.lang.RuntimeException: Unable to create service com.liulishuo.filedownloader.services.FileDownloadService$SharedMainProcessService: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/com.anhui.tv/databases/filedownloader.db' to 'zh_CN'.
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2582)
        at android.app.ActivityThread.access$1800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5030)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:649)
        at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteException: Failed to change locale for db '/data/data/com.anhui.tv/databases/filedownloader.db' to 'zh_CN'.
        at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:393)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:804)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:789)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1030)
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:256)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:224)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
        at com.liulishuo.filedownloader.services.DefaultDatabaseImpl.<init>(DefaultDatabaseImpl.java:50)
        at com.liulishuo.filedownloader.services.DownloadMgrInitialParams.createDefaultDatabase(DownloadMgrInitialParams.java:121)
        at com.liulishuo.filedownloader.services.DownloadMgrInitialParams.createDatabase(DownloadMgrInitialParams.java:64)
        at com.liulishuo.filedownloader.services.FileDownloadMgr.<init>(FileDownloadMgr.java:47)
        at com.liulishuo.filedownloader.services.FileDownloadService.onCreate(FileDownloadService.java:56)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2572)
        ... 10 more
Caused by: android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
        at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
        at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:555)
        at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:371)
        ... 28 more

**Comment by lx5288** [comment]
应该怎么处理这个异常，并且只让这个异常出现一次呢？

**Comment by lx5288** [comment]
我们统计发现有一款盒子已经上传了13000多条异常，其中同一个用户在同一时间段有300条以上的异常，而其他的android盒子也同样存在这个问题。

**Comment by lx5288** [comment]
上次的问题是下载过程中的异常，我们已经处理了，现在这个异常是初始化数据库的时候出现的异常！这会导致用户无限弹出错误页面，我们的应用已经上线，这个问题非常严重，希望大神能尽快提供一个方法给我，十分感谢！

**Comment by lx5288** [comment]
对于上次问题的答复，我并没有使用过除了SQLite外的其他数据库，所以不太方便进行组件定制

**Comment by lx5288** [comment]
能不能配置不使用断点下载

**Comment by lx5288** [comment]
可能不是在初始化的时候报的错误，而是在启动应用下载文件的时候报的错误

**Comment by Jacksgong** [comment]
> 对于上次问题的答复，我并没有使用过除了SQLite外的其他数据库，所以不太方便进行组件定制

所谓定制，只是说为FileDownloader定制数据库组件，而非说要使用SQLite以外的数据库，你可以依然使用SQLite然后自己进行相关的配置。

---

我看你这个有两个数据库长尾问题，目前FileDownloader没有考虑去处理这些长尾问题，FileDownloader并不是一个数据库的开源库，我们已经赋能给你们去定制自己想要的数据库了。不过针对两个长尾问题，我会给出我的建议:

### 问题一: `'/data/data/com.anhui.tv/databases/filedownloader.db' to 'zh_CN'.`

建议定制数据库，并且在打开数据库时候带上这个flag: `SQLiteDatabase.NO_LOCALIZED_COLLATORS`。

建议打开数据库如:

```
flags = SQLiteDatabase.CREATE_IF_NECESSARY | SQLiteDatabase.NO_LOCALIZED_COLLATORS | SQLiteDatabase.OPEN_READWRITE;
db = SQLiteDatabase.openDatabase(fileName, mFactory, flags, mErrorHandler);
```

具体可以参考`SQLiteOpenHelper#getDatabaseLocked`。

### 问题二: `android.database.sqlite.SQLiteFullException: database or disk is full (code 13)`

一般来说FileDownloader的数据库是不占用多少大小的，只是用于存储需要断点续传的数据，下载完成数据便会在数据库中删除。因此这个很有可能是其他文件占满了硬件的存储导致的。

1. 使用最新版本的FileDownloader，运行时如果有相关的数据库错误，会通过`FileDownloadListener#error`回调回来。
2. 如果在启动下载服务的时候报这个空间已满的错误，此时由于还没有任何回调注册，我看到你让下载服务共用了主进程，因此这里可以在进程启动时，注册`UncaughtExceptionHandler`给当前进程，然后在其错误回调方法中进行处理。

#### 对于这种空间满回调的处理

这种问题，实际上是用户空间不足的问题，其实很明显应该要解决空间问题，而非数据库问题，因此推荐以下三种解决方案:

1. 自己的应用有没有可以清理的占用系统大小的临时文件，在这个时间及时的删除了
2. 提示用户存储空间已满，让用户清理空间以后重试
3. 由于你的用户是盒子，可能磁盘空间原本就不足，作为应用应该合理的利用磁盘空间，自动的定期清理自己无用的数据，合理应用用户磁盘空间

#### 如果主动重新关闭与启动下载服务

- **释放数据库** 通过`FileDownloader#unbindService()`便可以解绑并且关闭下载服务以及释放其打开的数据库。
- **重新开启:** 启动下载，或者主动调用`FileDownloader#bindService`等方法即可。

### 能不能配置不使用断点下载，也就是不使用数据库

确实数据库是为了断点续传存在的，如果不使用数据库确实就没有这些问题，这个确实是一个解决方案，并且也是实际可行的，如果你不需要考虑下次重新启动进程的时候上次的进度丢失，而要实现这个也很简单:

实现你自己的`FileDownloadDatabase`，并且里面不启动任何的数据库，你可以参考我刚刚提交的`NoDatabaseImpl`，这个我会在1.6.4带上去，如果你着急使用，可以拷贝过去使用。如果因为你使用旧版本而无法使用`NoDatabaseImpl`，我能给过来的建议是，使用最新版本的FileDownloader.

**Comment by lx5288** [comment]
谢谢！

**Comment by lx5288** [comment]
我想问个问题，使用FileDownloader.getImpl().unBindService();
以后 服务会停止，不会自动重启是吧！

**Comment by Jacksgong** [comment]
`FileDownloader.getImpl().unBindService();`以后不会自动重启，因为服务被主动关了。前面的重启是因为`FileDownloadService`的模式是`START_STICKY`，并且服务没有被主动关闭。
