### ISSUE TITLE
[BUG]Exception

### ISSUE THREAD

**Issue by meijieman** [lingochamp/FileDownloader#730]
网络不佳情况下，出现如下 log
```
W/MessageQueue: Handler (android.os.Handler) {450f2ba0} sending message to a Handler on a dead thread
                java.lang.RuntimeException: Handler (android.os.Handler) {450f2ba0} sending message to a Handler on a dead thread
                    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:334)
                    at android.os.Handler.enqueueMessage(Handler.java:701)
                    at android.os.Handler.sendMessageAtTime(Handler.java:603)
                    at android.os.Handler.sendMessageDelayed(Handler.java:574)
                    at android.os.Handler.sendMessage(Handler.java:511)
                    at com.liulishuo.filedownloader.download.DownloadStatusCallback.onError(DownloadStatusCallback.java:192)
                    at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.onError(DownloadLaunchRunnable.java:659)
                    at com.liulishuo.filedownloader.download.DownloadRunnable.run(DownloadRunnable.java:128)
                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                    at java.lang.Thread.run(Thread.java:848)
```

**Comment by rantianhua** [comment]
请提供你使用的 FileDownloader 版本，这个很重要，谢谢！

**Comment by meijieman** [comment]
额，这个是17年的问题了，时间太久了找不到当时的版本。

我的解决办法是 fork 一份代码，然后自己修复了。

**Comment by meijieman** [comment]
这个单我关了吧

**Comment by rantianhua** [comment]
如果是你已经解决了问题？可否给 FileDownloader 提一个 MR ，帮助更多人解决这个问题？
