### ISSUE TITLE
IllegalFormatConversionException

### ISSUE THREAD

**Issue by ddrandy** [lingochamp/FileDownloader#743]
下载完成后的广播
FileDownloadModel downloadModel = FileDownloadBroadcastHandler.parseIntent(intent);
这里的downloadModel 调toString打印会挂

```
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
   at dalvik.system.NativeStart.main(Native Method)
Caused by: java.util.IllegalFormatConversionException: %d can't format java.util.concurrent.atomic.AtomicLong arguments
   at java.util.Formatter.badArgumentType(Formatter.java:1489)
   at java.util.Formatter.transformFromInteger(Formatter.java:1689)
   at java.util.Formatter.transform(Formatter.java:1461)
   at java.util.Formatter.doFormat(Formatter.java:1081)
   at java.util.Formatter.format(Formatter.java:1042)
   at java.util.Formatter.format(Formatter.java:1011)
   at java.lang.String.format(String.java:1999)
   at com.liulishuo.filedownloader.util.FileDownloadUtils.formatString(FileDownloadUtils.java:345)
   at com.liulishuo.filedownloader.model.FileDownloadModel.toString(FileDownloadModel.java:263)
```

**Comment by LittleCai** [comment]
我在暂停下载的时候也可能出现类似这种异常，不知道你是怎么解决的？

**Comment by Jacksgong** [comment]
这个问题会跟进解决。
