### ISSUE TITLE
关于下载时数据版本问题 FileDownloadService  Can't downgrade database from version 3 to 2

### ISSUE THREAD

**Issue by cywmm** [lingochamp/FileDownloader#752]
java.lang.RuntimeException: Unable to create service com.liulishuo.filedownloader.services.FileDownloadService$SeparateProcessService: android.database.sqlite.SQLiteException: Can't downgrade database from version 3 to 2
                              at android.app.ActivityThread.handleCreateService(ActivityThread.java:2568)
                              at android.app.ActivityThread.access$1800(ActivityThread.java:135)
                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
                              at android.os.Handler.dispatchMessage(Handler.java:102)
                              at android.os.Looper.loop(Looper.java:136)
                              at android.app.ActivityThread.main(ActivityThread.java:5001)
                              at java.lang.reflect.Method.invokeNative(Native Method)
                              at java.lang.reflect.Method.invoke(Method.java:515)
                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                              at dalvik.system.NativeStart.main(Native Method)
                           Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 3 to 2
                              at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:361)
                              at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:255)
                              at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
                              at com.liulishuo.filedownloader.services.DefaultDatabaseImpl.<init>(DefaultDatabaseImpl.java:50)
                              at com.liulishuo.filedownloader.services.DownloadMgrInitialParams.createDefaultDatabase(DownloadMgrInitialParams.java:121)
                              at com.liulishuo.filedownloader.services.DownloadMgrInitialParams.createDatabase(DownloadMgrInitialParams.java:78)
                              at com.liulishuo.filedownloader.services.FileDownloadMgr.<init>(FileDownloadMgr.java:52)
                              at com.liulishuo.filedownloader.services.FDServiceSeparateHandler.<init>(FDServiceSeparateHandler.java:61)
                              at com.liulishuo.filedownloader.services.FileDownloadService.onCreate(FileDownloadService.java:46)
                              at android.app.ActivityThread.handleCreateService(ActivityThread.java:2558)
                              at android.app.ActivityThread.access$1800(ActivityThread.java:135) 
                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278) 
                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                              at android.os.Looper.loop(Looper.java:136) 
                              at android.app.ActivityThread.main(ActivityThread.java:5001) 
                              at java.lang.reflect.Method.invokeNative(Native Method) 
                              at java.lang.reflect.Method.invoke(Method.java:515) 
                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                              at dalvik.system.NativeStart.main(Native Method)

**Comment by rantianhua** [comment]
你使用的是哪个版本？是什么情况下出现这个问题？从高版本的 FileDownloader 切换到低版本的 FileDownloader ？
