### ISSUE TITLE
频繁点击任务管理器案列列表闪退

### ISSUE THREAD

**Issue by woyoudianhuai** [lingochamp/FileDownloader#758]
Process: com.liulishuo.filedownloader.demo, PID: 25899
                                                   java.lang.IllegalArgumentException: d != java.util.concurrent.atomic.AtomicLong
                                                       at android.os.Parcel.readException(Parcel.java:1669)
                                                       at android.os.Parcel.readException(Parcel.java:1618)
                                                       at com.liulishuo.filedownloader.i.IFileDownloadIPCService$Stub$Proxy.pause(IFileDownloadIPCService.java:313)
                                                       at com.liulishuo.filedownloader.FileDownloadServiceUIGuard.pause(FileDownloadServiceUIGuard.java:119)
                                                       at com.liulishuo.filedownloader.FileDownloadServiceProxy.pause(FileDownloadServiceProxy.java:72)
                                                       at com.liulishuo.filedownloader.DownloadTaskHunter.pause(DownloadTaskHunter.java:419)
                                                       at com.liulishuo.filedownloader.DownloadTask.pause(DownloadTask.java:338)
                                                       at com.liulishuo.filedownloader.FileDownloader.pause(FileDownloader.java:297)
                                                       at com.liulishuo.filedownloader.demo.TasksManagerDemoActivity$TaskItemAdapter$2.onClick(TasksManagerDemoActivity.java:307)
                                                       at android.view.View.performClick(View.java:5646)
                                                       at android.view.View$PerformClick.run(View.java:22459)
                                                       at android.os.Handler.handleCallback(Handler.java:761)
                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                       at android.os.Looper.loop(Looper.java:156)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by Jacksgong** [comment]
该问题已经在1.6.5中修复，参考下这里: #743
