### ISSUE TITLE
open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by susirsusir** [lingochamp/FileDownloader#802]
use version com.liulishuo.filedownloader:library:1.6.8
java.io.IOException: open failed: ENOENT (No such file or directory)
at java.io.File.createNewFile(File.java:946) at com.liulishuo.filedownloader.util.FileDownloadUtils.createOutputStream(FileDownloadUtils.java:576)
at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.handlePreAllocate(DownloadLaunchRunnable.java:704)
  at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:276)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 at java.lang.Thread.run(Thread.java:841)
 Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
 at libcore.io.Posix.open(Native Method)
 at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
  at java.io.File.createNewFile(File.java:939)

**Comment by rantianhua** [comment]
请使用 1.7.6 版本，现在在对创建文件做了强制检查，如果没有创建成功是不会去创建流的。
