### ISSUE TITLE
crash app

### ISSUE THREAD

**Issue by rasoulinejad** [lingochamp/FileDownloader#823]
junit.framework.AssertionFailedError: can't handover the message, no master to receive this message(status[3]) size[0]
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at com.liulishuo.filedownloader.FileDownloadMessenger.handoverMessage(FileDownloadMessenger.java:250com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.dispose(FileDownloadMessageStation.java:169)	at com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.handleMessage(FileDownloadMessageStation.java:160)

**Comment by Jacksgong** [comment]
Ref to #889

**Comment by rasoulinejad** [comment]
thanks for fix this issue.
