### ISSUE TITLE
java.io.IOException: The file is too large to store, the downloaded size:  0, requirements: 4449023, but the available space size: -568107008

### ISSUE THREAD

**Issue by nukc** [lingochamp/FileDownloader#84]
更新到0.2.1后点击下载就报如下错误，存储空间是够的。。
```java
java.io.IOException: The file is too large to store, the downloaded size:  0, requirements: 4449023, but the available space size: -568107008
  at com.liulishuo.filedownloader.services.FileDownloadRunnable.getRandomAccessFile(FileDownloadRunnable.java:541)
  at com.liulishuo.filedownloader.services.FileDownloadRunnable.fetch(FileDownloadRunnable.java:285)
  at com.liulishuo.filedownloader.services.FileDownloadRunnable.loop(FileDownloadRunnable.java:249)
  at com.liulishuo.filedownloader.services.FileDownloadRunnable.run(FileDownloadRunnable.java:138)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
  at java.lang.Thread.run(Thread.java:856)
```

**Comment by nukc** [comment]
Phone: HUAWEI U9508  (Android 4.0.4)  测试的是这部机报错
Genymotion 4.4.4 正常运行
魅蓝 note1 4.4.4 （Flyeme OS 4.2.0.5U） 正常运行

**Comment by nukc** [comment]
Genymotion 2.3.7 报错。
看了下源码，不知道是不是在at com.liulishuo.filedownloader.services.FileDownloadRunnable.getRandomAccessFile

```java
            long availableBytes;
            final StatFs statFs = new StatFs(path);
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR2) {
                availableBytes = statFs.getAvailableBytes();
            } else {
                // API < Android 4.3的都会？
                availableBytes = statFs.getAvailableBlocks() * statFs.getBlockSize();  
            }
```

**Comment by Jacksgong** [comment]
我确实没有在Jelly Bean以下的试过，我看API文档应该是没有问题才对。我试试。

**Comment by Jacksgong** [comment]
:100: 多谢反馈，我现在修复，发个版本!

**Comment by nukc** [comment]
好的，谢谢，辛苦了。

**Comment by Jacksgong** [comment]
Fixed in [v0.2.2](https://github.com/lingochamp/FileDownloader/releases/tag/v0.2.2).
