### ISSUE TITLE
(FileDownloadUtils.java:345)版本1.6.8

### ISSUE THREAD

**Issue by ccscorpio** [lingochamp/FileDownloader#854]
进行串行下载时报错
DALVIK THREADS (51):
"main" prio=5 tid=1 WaitingForDebuggerSend
  | group="main" sCount=1 dsCount=0 obj=0x71a26000 self=0xb4f07800
  | sysTid=7105 nice=0 cgrp=apps sched=0/0 handle=0xb6f0fec8
  | state=S schedstat=( 15508300084 5811220695 44617 ) utm=1411 stm=139 core=1 HZ=100
  | stack=0xbe1c7000-0xbe1c9000 stackSize=8MB
  | held mutexes=
  native: #00 pc 00012e98  /system/lib/libc.so (syscall+28)
  native: #01 pc 000a91ed  /system/lib/libart.so (art::Mutex::ExclusiveLock(art::Thread*)+364)
  native: #02 pc 00195a49  /system/lib/libart.so (art::JDWP::JdwpState::SendBufferedRequest(unsigned int, std::__1::vector<iovec, std::__1::allocator<iovec> > const&)+288)
  native: #03 pc 0018bfc1  /system/lib/libart.so (art::JDWP::JdwpState::DdmSendChunkV(unsigned int, iovec const*, int)+736)
  native: #04 pc 000f1a1f  /system/lib/libart.so (art::Dbg::DdmSendChunk(unsigned int, unsigned int, unsigned char const*)+46)
  native: #05 pc 000f25ad  /system/lib/libart.so (art::Dbg::DdmSendHeapInfo(art::Dbg::HpifWhen)+1048)
  native: #06 pc 000f5bf1  /system/lib/libart.so (art::Dbg::GcDidFinish()+336)
  native: #07 pc 00142159  /system/lib/libart.so (art::gc::Heap::CollectGarbageInternal(art::gc::collector::GcType, art::gc::GcCause, bool)+1888)
  native: #08 pc 00143327  /system/lib/libart.so (art::gc::Heap::PushOnThreadLocalAllocationStackWithInternalGC(art::Thread*, art::mirror::Object**)+290)
  native: #09 pc 0017750f  /system/lib/libart.so (art::mirror::Array* art::mirror::Array::Alloc<true>(art::Thread*, art::mirror::Class*, int, unsigned int, art::gc::AllocatorType, bool)+2106)
  native: #10 pc 0009c8fb  /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<true, false>(art::Thread*, art::MethodHelper&, art::DexFile::CodeItem const*, art::ShadowFrame&, art::JValue)+32234)
  native: #11 pc 00163edd  /system/lib/libart.so (art::interpreter::EnterInterpreterFromStub(art::Thread*, art::MethodHelper&, art::DexFile::CodeItem const*, art::ShadowFrame&)+236)
  native: #12 pc 002942b1  /system/lib/libart.so (artQuickToInterpreterBridge+488)
  native: #13 pc 000a2ecb  /system/lib/libart.so (art_quick_to_interpreter_bridge+10)
  native: #14 pc 001e546d  /system/lib/libart.so (art::mirror::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+152)
  at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:83)
  at java.lang.StringBuilder.<init>(StringBuilder.java:67)
  at java.lang.String.format(String.java:1802)
  at com.liulishuo.filedownloader.util.FileDownloadUtils.formatString(FileDownloadUtils.java:345)
  at com.liulishuo.filedownloader.FileDownloadMessenger.handoverMessage(FileDownloadMessenger.java:256)
  at com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.dispose(FileDownloadMessageStation.java:169)
  at com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.handleMessage(FileDownloadMessageStation.java:160)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:135)
  at android.app.ActivityThread.main(ActivityThread.java:5221)
  at java.lang.reflect.Method.invoke!(Native method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by Jacksgong** [comment]
@ccscorpio 可否提供下手机的系统版本，我看下源码，挺奇怪的，根据错误栈，这里的字符串匹配是没有问题的。

**Comment by ccscorpio** [comment]
android 5.0   一次下载1000张图片，中途停止，清除所有任务，循环反复

**Comment by rantianhua** [comment]
看日志信息，似乎你是正在调试的时候出现了问题，对吗？是不是开启了 Instant Run ?

**Comment by rantianhua** [comment]
No response for a long time.
