### ISSUE TITLE
1.6.8版本  NullPointerException

### ISSUE THREAD

**Issue by zmylw** [lingochamp/FileDownloader#861]
系统版本：android:5.1
偶发性问题，这个问题会导致app崩溃，日志是通过app crash时自动抓到的，很难复现。麻烦看下，谢谢！

#Thu Dec 07 10:49:03 GMT+08:00 2017
#------------AndroidRuntime crash start------------
Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object referencejava.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
	at com.inovance.advideoplayer.service.DownLoadService.a(SourceFile:1054)
	at com.inovance.advideoplayer.service.DownLoadService.d(SourceFile:1130)
	at com.inovance.advideoplayer.service.DownLoadService.a(SourceFile:935)
	at com.inovance.advideoplayer.iot.e.b$3.a(SourceFile:407)
	at com.liulishuo.filedownloader.k.b(SourceFile:345)
	at com.liulishuo.filedownloader.j$b.a(SourceFile:169)
	at com.liulishuo.filedownloader.j$b.handleMessage(SourceFile:160)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5637)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

#------------AndroidRuntime crash end------------

**Comment by Haoxiqiang** [comment]
显然是你DownLoadService自己的 service 挂了

**Comment by Jacksgong** [comment]
`com.inovance.advideoplayer.service.DownLoadService.a`这个并非FileDownloader的类，你留意下，应该是这里上层封装这里出现了问题。
