### ISSUE TITLE
请问这是什么非法参数异常错误，没找到具体原因

### ISSUE THREAD

**Issue by 1453946442** [lingochamp/FileDownloader#889]
#### Issue

    12-25 19:23:43.587 13320-13320/? E/AndroidRuntime: FATAL EXCEPTION: main Process: com.hy.HoneyMarket, PID: 13320  
    java.lang.IllegalArgumentException: can't handover the message, no master to receive this message(status[2]) size[0]  

    at com.liulishuo.filedownloader.k.b(Unknown Source)
    at com.liulishuo.filedownloader.j$b.a(Unknown Source)
    at com.liulishuo.filedownloader.j$b.handleMessage(Unknown Source)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5258)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

---

**Comment by rantianhua** [comment]
请提供下使用的 Filedownloader 的版本！

**Comment by rantianhua** [comment]
出现这个错误的原因是并发引起的状态错误。针对你提供的日志，下载状态在变成完成状态（比如已暂停、已出错等等）后又收到下载已连接的（可以理解为正在运行）的状态（状态值为2），这个时候就抛出了这个错误。我需要先问你两个问题：
 1. 在你的使用方式里，下载进程是在独立进程还是主进程？
 2. `start` 和 `pause` 操作是否在同一个线程？方便的话，最好能提供一下你调用过程的伪代码。
