### ISSUE TITLE
乐视手机点开 最近打开的栈列表 报错。

### ISSUE THREAD

**Issue by BinarySatan** [lingochamp/FileDownloader#935]
乐视手机点开 最近打开栈列表， 然后从列表进入别的APP，再次打开栈列表， 报错如下:

请在Issue前认真的跟进上面提到的建议，这样将可以极大的加快你遇到问题的处理。

error : java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
Caused by: android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)

**Comment by rantianhua** [comment]
其实没有明白你的问题是什么？单从你提供的描述信息和错误日志来看，没有哪里能明显看出是 FileDownloader 的异常。所以希望能提供更多关于使用 FileDownloader 的信息。比如，Filedownloader 版本，FileDownloader 日志。
