### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=8192; index=8192

### ISSUE THREAD

**Issue by techGay** [lingochamp/FileDownloader#940]
版本：1.6.9

bug系统捕抓回传日志：
java.lang.ArrayIndexOutOfBoundsException: length=8192; index=8192
        at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:818)
        at com.android.okhttp.okio.Buffer.writeUtf8(Buffer.java:793)
        at com.android.okhttp.okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:57)
        at com.android.okhttp.internal.http.HttpConnection.writeRequest(HttpConnection.java:172)
        at com.android.okhttp.internal.http.HttpTransport.writeRequestHeaders(HttpTransport.java:76)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:766)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
        at com.liulishuo.filedownloader.a.c.e(FileDownloadUrlConnection.java:102)
        at com.liulishuo.filedownloader.a.d.a(RedirectHandler.java:55)
        at com.liulishuo.filedownloader.download.a.a(ConnectTask.java:77)
        at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:275)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)

用户系统信息：
manufacturer   HUAWEI
model   EVA-TL00
networkAccess   wifi
orientation   portrait
osBuild   EVA-TL00C01B398
osName   android
osVersion   7.0
screenDensity   3
screenResolution   1794x1080

---程序用于下载视频

这是目前可提供的所有信息，因为只发现有一个用户有此问题，到目前也仅仅发生了两次，测试中也未发现过，无法复现

**Comment by rantianhua** [comment]
看了你的日志，具体抛出异常的地方是 okhttp 内部，外部 FileDownloader 只是调用了 `FileDownloadConnection#getResponseCode()` ，其中 `FileDownloadConnection` 默认是实现是 `FileDownloadUrlConnection ` ，看你的日志你使用的应该也是这个默认实现，这个默认实现里使用的是 `URLConnection` 进行 http 连接，然后你的系统内部应该是用 okhttp 进行具体的 http 请求。所以说这个问题实际上是 okhttp 的问题。建议在 okhttp 提相关 issue。

**Comment by nicelyjust** [comment]
@techGay Hey,I got same issue,Did you fix it?

**Comment by carryinfo** [comment]
我这也是这个问题，
