### ISSUE TITLE
crash app (version 1.7.0)

### ISSUE THREAD

**Issue by rasoulinejad** [lingochamp/FileDownloader#943]
java.lang.IllegalArgumentException: can't handover the message, no master to receive this message(status[6]) size[0]	at com.liulishuo.filedownloader.FileDownloadMessenger.handoverMessage(FileDownloadMessenger.java:254)	at com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.dispose(FileDownloadMessageStation.java:169) at com.liulishuo.filedownloader.FileDownloadMessageStation$UIHandlerCallback.handleMessage(FileDownloadMessageStation.java:160)

Android: 7.0
Manufacturer: samsung
Model: SM-N920C

**Comment by Jacksgong** [comment]
This is very small probability case, and it's very hard to finger out the real cause since the unit test is covered very low on FileDownloader, if you very concern such small probability case, please use FileDownloader2 - okdownload instead.

But this problem very never forgives, but 1.7.3 will not carry this fixes.

**Comment by rantianhua** [comment]
@rasoulinejad Do you invoke the method: `BaseDownloadTask#setSyncCallback` ?
