### ISSUE TITLE
FileDownloadGiveUpRetryException

### ISSUE THREAD

**Issue by BinarySatan** [lingochamp/FileDownloader#956]
com.liulishuo.filedownloader.exception.FileDownloadGiveUpRetryException: sofar[12074824] not equal total[46820344]
at com.liulishuo.filedownloader.download.DownloadStatusCallback.interceptBeforeCompleted(DownloadStatusCallback.java:401)
at com.liulishuo.filedownloader.download.DownloadStatusCallback.onCompletedDirectly(DownloadStatusCallback.java:194)
at com.liulishuo.filedownloader.download.DownloadLaunchRunnable.run(DownloadLaunchRunnable.java:330)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1120)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:820)

**Comment by rantianhua** [comment]
请提供完整的日志。

**Comment by rantianhua** [comment]
Close because of too long without a reply.
