### ISSUE TITLE
FileDownloader.FileDownloadService: callback error

### ISSUE THREAD

**Issue by nukc** [lingochamp/FileDownloader#98]
刚刚升级到了0.2.3，然后在Genymotion 6.0上测试，进入页面点击下载，正常，然后点暂停再点继续，然后就报如下错误，程序没有崩溃（App开始卡爆了）。 
```java
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 140)
E/FileDownloader.FileDownloadService: callback error
W/System.err: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
W/System.err:     at android.os.BinderProxy.transact(Binder.java:503)
W/System.err:     at com.liulishuo.filedownloader.i.IFileDownloadIPCCallback$Stub$Proxy.callback(IFileDownloadIPCCallback.java:88)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.handleCallback(FileDownloadService.java:69)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.handleCallback(FileDownloadService.java:41)
W/System.err:     at com.liulishuo.filedownloader.services.BaseFileService.callback(BaseFileService.java:113)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.callback(FileDownloadService.java:77)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.publish(DownloadEventPoolImpl.java:129)
W/System.err:     at com.liulishuo.filedownloader.FileDownloadEventPool.publish(FileDownloadEventPool.java:93)
W/System.err:     at com.liulishuo.filedownloader.FileDownloadFlowThreadPool$FlowSingleExecutor$1.run(FileDownloadFlowThreadPool.java:102)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
```
还有下面这个看似无限log的warn
```java
W/FileDownloader.FileDownloadTask: The flow callback did not consumed, id:-764908921 status:3 task-count:1 | -2
```

强制关闭，再次打开App，进入同个页面，在还没点继续之前不会卡顿，点继续后，进度是一时 50% 一时 52%，差不多就是下一秒增加了，再下一秒就减少了。同时，开始卡顿。

再测试4.4.4，问题依旧。

**Comment by Jacksgong** [comment]
```
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 140)
E/FileDownloader.FileDownloadService: callback error
W/System.err: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
W/System.err:     at android.os.BinderProxy.transact(Binder.java:503)
W/System.err:     at com.liulishuo.filedownloader.i.IFileDownloadIPCCallback$Stub$Proxy.callback(IFileDownloadIPCCallback.java:88)
```
上面这个log，应该是你应用的主进程挂了。

其他的问题有更详细的信息吗，必现的吗。

可否试试，github中的 demo project，看看差别是哪里的差别导致这个问题的。

**Comment by Jacksgong** [comment]
> P.S: 如果你测试 github中的 demo project (其实我都有用demo project 至少做一些基本测试以后才会发版本的)没有问题的话，你先clean你自己的项目，然后rebuild，也有可能是ide的坑。

**Comment by nukc** [comment]
按钮显示 ```继续```，点击后依旧显示 ```继续```，在0.2.2版本里是正常的显示 ```暂停```。
同时在点击后无限log:
```java
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
E/FileDownloader.FileDownloadService: callback error
W/System.err: android.os.TransactionTooLargeException
W/System.err:     at android.os.BinderProxy.transact(Native Method)
W/System.err:     at com.liulishuo.filedownloader.i.IFileDownloadIPCCallback$Stub$Proxy.callback(IFileDownloadIPCCallback.java:88)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.handleCallback(FileDownloadService.java:69)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.handleCallback(FileDownloadService.java:41)
W/System.err:     at com.liulishuo.filedownloader.services.BaseFileService.callback(BaseFileService.java:113)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.callback(FileDownloadService.java:77)
W/System.err:     at com.liulishuo.filedownloader.i.IFileDownloadIPCCallback$Stub$Proxy.callback(IFileDownloadIPCCallback.java:88)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at com.liulishuo.filedownloader.services.BaseFileService.callback(BaseFileService.java:113)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.handleCallback(FileDownloadService.java:69)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.callback(FileDownloadService.java:77)
W/System.err: android.os.TransactionTooLargeException
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.FileDownloadFlowThreadPool$FlowSingleExecutor$1.run(FileDownloadFlowThreadPool.java:102)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.publish(DownloadEventPoolImpl.java:129)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.handleCallback(FileDownloadService.java:69)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
W/System.err:     at java.lang.Thread.run(Thread.java:841)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.publish(DownloadEventPoolImpl.java:129)
W/System.err:     at com.liulishuo.filedownloader.FileDownloadEventPool.publish(FileDownloadEventPool.java:93)
W/System.err:     at com.liulishuo.filedownloader.FileDownloadFlowThreadPool$FlowSingleExecutor$1.run(FileDownloadFlowThreadPool.java:102)
W/System.err:     at com.liulishuo.filedownloader.services.BaseFileService.callback(BaseFileService.java:113)
W/System.err:     at com.liulishuo.filedownloader.FileDownloadFlowThreadPool$FlowSingleExecutor$1.run(FileDownloadFlowThreadPool.java:102)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.publish(DownloadEventPoolImpl.java:129)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.FileDownloadFlowThreadPool$FlowSingleExecutor$1.run(FileDownloadFlowThreadPool.java:102)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.handleCallback(FileDownloadService.java:69)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.handleCallback(FileDownloadService.java:69)
W/System.err:     at com.liulishuo.filedownloader.i.IFileDownloadIPCCallback$Stub$Proxy.callback(IFileDownloadIPCCallback.java:88)
W/System.err:     at com.liulishuo.filedownloader.FileDownloadEventPool.publish(FileDownloadEventPool.java:93)
W/System.err:     at com.liulishuo.filedownloader.FileDownloadFlowThreadPool$FlowSingleExecutor$1.run(FileDownloadFlowThreadPool.java:102)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.FileDownloadFlowThreadPool$FlowSingleExecutor$1.run(FileDownloadFlowThreadPool.java:102)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.handleCallback(FileDownloadService.java:69)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at com.liulishuo.filedownloader.i.IFileDownloadIPCCallback$Stub$Proxy.callback(IFileDownloadIPCCallback.java:88)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.callback(FileDownloadService.java:77)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.callback(FileDownloadService.java:77)
W/System.err:     at com.liulishuo.filedownloader.services.FileDownloadService.callback(FileDownloadService.java:77)
W/System.err: android.os.TransactionTooLargeException
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.i.IFileDownloadIPCCallback$Stub$Proxy.callback(IFileDownloadIPCCallback.java:88)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.FileDownloadFlowThreadPool$FlowSingleExecutor$1.run(FileDownloadFlowThreadPool.java:102)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventSampleListener.callback(DownloadEventSampleListener.java:36)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.trigger(DownloadEventPoolImpl.java:184)
W/System.err:     at com.liulishuo.filedownloader.event.DownloadEventPoolImpl.publish(DownloadEventPoolImpl.java:129)
W/System.err:     at com.liulishuo.filedownloader.FileDownloadEventPool.publish(FileDownloadEventPool.java:93)
W/System.err:     at com.liulishuo.filedownloader.FileDownloadFlowThreadPool$FlowSingleExecutor$1.run(FileDownloadFlowThreadPool.java:102)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
```
直至最后crash，而文件也不知道是在哪个时候下载完了。
我先rebuild看看，再回来汇报下。

**Comment by Jacksgong** [comment]
💯  好的。

**Comment by nukc** [comment]
抱歉，刚刚开会。
我刚刚试了几次，clean rebuild后问题依旧。
运行了github上的demo，是没有问题的。
我换回0.2.2版本，一切都很正常。我想问下，0.2.3版本回调逻辑有没有改变？有的话，那我也需要更新一下App的代码逻辑。

**Comment by Jacksgong** [comment]
👍  0.2.3回调逻辑代码没有改变，只是多了一个回调 `started` 以及修复了一些特殊情况下存在的bug。
具体你留意下change log或者是 reademe。

**Comment by nukc** [comment]
嗯，好的。我基本上都有看change log，也没发现什么改变，倒是修复了不少问题，那我再去看一遍和我的代码。这个issues先不要关闭，我去解决问题，解决了再回来，没解决也会回来汇报。

**Comment by Jacksgong** [comment]
恩。好的。这样最好。

**Comment by nukc** [comment]
我下载了0.2.2版本的library导入项目中，然后4月7日开始是后续commit，按照顺序，每个commit的变化我都看一遍然后在导入的library上修改，修改完后运行一次。直到 [027c700](https://github.com/lingochamp/FileDownloader/commit/027c7002612c1854cd2e4b70b819ce1696094e8e) 这个commit，APP就发生了上面那些错误。

**Comment by nukc** [comment]
我尝试了下：
使用了之前删除的`FileDownloadProcessEventPool`，
在`FileDownloadService`的`onCreate()`和`onDestroy()`里还是用之前`FileDownloadProcessEventPool`：
```java
 @Override
    public void onCreate() {
        super.onCreate();
        mListener = new DownloadEventSampleListener(this);

//        FileDownloadEventPool.getImpl().addListener(DownloadTransferEvent.ID, mListener);
        FileDownloadProcessEventPool.getImpl().addListener(DownloadTransferEvent.ID, mListener);
    }

    @Override
    public void onDestroy() {
        super.onDestroy();

//        FileDownloadEventPool.getImpl().removeListener(DownloadTransferEvent.ID, mListener);
        FileDownloadProcessEventPool.getImpl().removeListener(DownloadTransferEvent.ID, mListener);
    }
```
然后在`FileDownloadRunnable`的`onStatusChanged(int status)`方法：
```java
    private void onStatusChanged(int status) {
        transferModel.update(model);

//            FileDownloadEventPool.getImpl().
//                    asyncPublishInFlow(new DownloadTransferEvent(transferModel.copy()));
        FileDownloadProcessEventPool.getImpl().
                    asyncPublishInNewThread(new DownloadTransferEvent(transferModel.copy()));
    }
```

然后APP就正常了，我试过调用`asyncPublishInFlow`方法，但是仍旧不正常，所以调用了`FileDownloadProcessEventPool`的`asyncPublishInNewThread`方法，另外看到在`FileDownloadServiceUIGuard`的
```java
public static class FileDownloadServiceCallback extends IFileDownloadIPCCallback.Stub {

        @Override
        public void callback(FileDownloadTransferModel transfer) throws RemoteException {
            FileDownloadEventPool.getImpl().asyncPublishInFlow(new DownloadTransferEvent(transfer));
        }
    }
```
也调用了`asyncPublishInFlow`方法，最后在`FlowSingleExecutor`的`execute`方法里打印log发现，下载过程中会不断log（那就是说下载的回调线程是callback方法启动的？那`onStatusChanged(int status)`里启动的线程不使用`asyncPublishInFlow`会不会有问题（违背你的用意）？）。

**Comment by Jacksgong** [comment]
首先，挺奇怪的，这个不应该和你的那个问题**没有关联性**。
> 而且，我们自己也用这个库做高并发下载，并没有遇到这个问题。

---

> 如果不用这个Flow池，而用之前的那个，在高并发的时候有可能在一些情况下回调 不次序不达预期。

#### 原因:

之前的池子在高并发的时候，就有可能 一个任务多个回调状态 并行执行，会导致不达预期的 回调次序 (比如 先 回调了progress了再 回调 connected)。

而这个 Flow 的线程池的池子与 任务绑定，就是为了解决上面这个问题的。

所有的回调，从 FileDownloader进程，到主进程，都是用 Flow线程池的池子驱动的，所以 不断会有 `execute` 被调用是正常的，设计如此。

---

#### 最后，出于解决问题，而且我觉得挺诡异的，我提出两问题:

1. 是否使用模拟器，机型是什么，系统是什么?
2. 你直接运行 github中的FileDownlaoder的demo项目也会出现这个问题吗?
3. 如果你运行demo项目不会有这个问题，那么可否提供下你可以必现问题的 简单demo，以你想要的方式发送给我， 如果你运行demo项目也会有这个问题，我会模拟你的机型进行测试。

**Comment by nukc** [comment]
我也觉得很诡异，看代码，我没看出有什么问题，但就是感觉哪里有点怪怪的。
demo项目不会出现这个问题，不是模拟器的问题，真机也会。
我做了个简化版的demo，可是却无法重现。看来应该跟我项目代码有联系，我会进一步排查。

**Comment by Jacksgong** [comment]
👍 ok.

**Comment by ArthurPai** [comment]
我也遇到了下面這個問題，一直在126狀態之間循環
```
FileDownloadTask: The flow callback did not consumed, id:-8629196 status:1 task-count:1 | 3
FileDownloadTask: The flow callback did not consumed, id:-8629196 status:6 task-count:1 | 3
FileDownloadTask: The flow callback did not consumed, id:-8629196 status:2 task-count:1 | 3
FileDownloadTask: The flow callback did not consumed, id:-8629196 status:1 task-count:1 | 3
FileDownloadTask: The flow callback did not consumed, id:-8629196 status:6 task-count:1 | 3
FileDownloadTask: The flow callback did not consumed, id:-8629196 status:2 task-count:1 | 3
FileDownloadTask: The flow callback did not consumed, id:-8629196 status:1 task-count:1 | 3
```

下載進度也是會增加減少
像是下面這樣
31%, 22%, 15%, 3%, 32%, 24%

**Comment by Jacksgong** [comment]
@ArthurPai 你对比下项目中的demo，这些在demo中都做过非常多的测试的。如果demo中也会，可以详细给下复现路径，我看看。

**Comment by ArthurPai** [comment]
我找到問題了，我本來有加上bind server的步驟，只要沒有bind server就不會出現我剛提到的現象

不過不知道是不是Init後立刻做bind會有問題
```
FileDownloader.init(context);
FileDownloader.getImpl().bindService();
````

**Comment by Jacksgong** [comment]
@ArthurPai 💯  恩。这样如果你是直接在 Application中的 `onCreate` 中调肯定是有问题的，因为 Application 在 App进程会被调用 一次，在 下载进程 又会被调一次。

#### 有两点建议:

1. 你可以完全不用主动(显式)调用 `bindService()` 在你启动第一个任务的时候，下载进程会自动启动并且服务会自动绑定上。
2. 如果你确实有需求需要事先就启动下载进程以及下载服务，在对应的 `Activity` 中调用，或者在 `Application`中判断当前所在进程为主进程，再调用 `bindService()`。

**Comment by nukc** [comment]
移除`bindService()`后，App正常运行，感谢@ArthurPai 。
